### ISSUE TITLE
Store and provide logs in packit service

### ISSUE THREAD

**Issue by TomasTomecek** [packit-service/packit-service#1]
get logs from copr realtime and provide them realtime in a sensible way (show what matters to users, not internal infra stuff people don't understand)

**Comment by lachmanfrantisek** [comment]
Is this issue about storing logs or real-time responses?

**Comment by TomasTomecek** [comment]
both - copr doesn't provide a user friendly way of providing logs so instead we could do such a thing in packit service

again, worth discussing
