### ISSUE TITLE
copr builds: create a comment instead of setting a status

### ISSUE THREAD

**Issue by TomasTomecek** [packit-service/packit-service#105]
if there is an error during execution, we set status on the PR with description from the exception: github doesn't allow us to put there too much text; we should instead create a comment on the PR and include the text inside while setting status to something short, e.g. "There was an error during the build process".

**Comment by msehnout** [comment]
Example:
![packit-error-msg](https://user-images.githubusercontent.com/9369632/63919381-f0e78a80-ca3e-11e9-862f-7d82da3092be.png)
See the title in the div and compare it with what you can actually see in the status.

**Comment by jpopelka** [comment]
Could we as a start just remove the "There was an error while running the build:"?
We already know that because there's the red cross, so we could just put the actual reason there.
