### ISSUE TITLE
copr builds from master instead of PR branch

### ISSUE THREAD

**Issue by nforro** [packit-service/packit-service#106]
I noticed in this PR https://github.com/rebase-helper/rebase-helper/pull/696 that version and tarball for copr builds are created from master branch (as you can tell from package version). I would expect it to be created from pull request branch, otherwise it kind of defeats the point of doing copr builds for a PR.

**Comment by TomasTomecek** [comment]
Hm, this is odd.

Packit service definitely checks out the PR ref. This should be easy to reproduce: just remove some BRs and see how the build fails.

When I check your PR locally and run `packit srpm` I get:
```
rebase-helper-0.18.1.dev9+gb241e04-1.fc30.src.rpm
```

Which I assume means that the commit is 9th from the last tag (which holds after looking at `git log`). When I open the copr build, it says `rebase-helper-0.18.1.dev8g0d7fe24-1.fc30.src.rpm` -- pretty weird that the + is missing. Is this how you figured out that p-s is using master branch instead of the PR ref?

**Comment by nforro** [comment]
If I take a look at the latest [build](https://copr.fedorainfracloud.org/coprs/packit/rebase-helper-rebase-helper-696/build/1023513/), I can see version is `0.18.1.dev8+g0d7fe24-1.fc30`, where `0d7fe24` refers to commit https://github.com/rebase-helper/rebase-helper/commit/0d7fe246508218e7f9d737b3be3e0265053927d6, which happens to be `master`.
And the change to the spec file made in that PR is not [reflected](https://copr-be.cloud.fedoraproject.org/results/packit/rebase-helper-rebase-helper-696/fedora-30-x86_64/01023513-rebase-helper/rebase-helper.spec) in the copr build, so I believe removing a BR wouldn't make any difference, but I can try it.

**Comment by TomasTomecek** [comment]
I wonder how this is even possible because I'm 100% sure that for most users packit-service builds from PR refs.

It may be possible that we regressed in functionality recently.

**Comment by nforro** [comment]
So I removed a BR in https://github.com/rebase-helper/rebase-helper/commit/7b1db9ddbb57a511f38e97572b79b72225e8001a, but the version in the latest [copr build](https://copr.fedorainfracloud.org/coprs/packit/rebase-helper-rebase-helper-696/build/1024620/) is still the same, the build is still pending but it will most likely finish succesfully.
When I run `packit srpm` locally, it creates `rebase-helper-0.18.1.dev11+g7b1db9d-1.fc30.src.rpm` and build of that SRPM fails as expected.

**Comment by TomasTomecek** [comment]
okay, looking at code and I feel like I can confirm this is true since I can't spot code which would check out the ref

luckily the fix is a one-liner
