### ISSUE TITLE
packitos-free service (image)

### ISSUE THREAD

**Issue by jpopelka** [packit-service/packit-service#109]
After merging #104 we have separate images for service (httpd) and celery worker.
The service image is still huge since it requires frambo (#38) and packit.

Packit pulls in a lot of other dependencies.
The only thing that service needs from packit is [config](https://github.com/packit-service/packit-service/blob/master/packit_service/service/events.py#L34), so I hope it shouldn't be that hard to somehow decouple it. Am I too naive?

**Comment by TomasTomecek** [comment]
Makes sense. I personally feel like it's an overkill: service image won't be updated often so it shouldn't be such a hassle.

**Comment by jpopelka** [comment]
Ok, let's close this since #9 is superset (completely separate repos, not just images) of this.
