### ISSUE TITLE
Base service image on f30

### ISSUE THREAD

**Issue by jpopelka** [packit-service/packit-service#110]
[Dockerfile](https://github.com/packit-service/packit-service/blob/master/Dockerfile)

```Dockerfile
FROM registry.fedoraproject.org/f29/httpd:2.4
```

**Comment by TomasTomecek** [comment]
and ideally use vanilla f30, not httpd based one

**Comment by jpopelka** [comment]
> ideally use vanilla f30, not httpd based one

for what reasons?

**Comment by TomasTomecek** [comment]
didn't we talk about this in person? two reasons:

1. the scl image is very complicated

2. if we have the image defined ourselves, we can rebuild it and make it clear of CVEs whenever we want (this is something we need to focus on sooner or later)

**Comment by jpopelka** [comment]
> didn't we talk about this in person? two reasons:

I don't remember

>     1. the scl image is very complicated

[The Dockerfile](https://github.com/sclorg/httpd-container/blob/master/2.4/Dockerfile.fedora) doesn't seem complicated to me. I doubt "our" will be less "complicated".

>     2. if we have the image defined ourselves, we can rebuild it and make it clear of CVEs whenever we want (this is something we need to focus on sooner or later)

It's open-source, we can use their Dockerfile and rebuild it (which is what I did) anytime.

**Comment by jpopelka** [comment]
Ok, I'll try to put httpd directly into our image.
