### ISSUE TITLE
No Handler for JobTriggerType.comment

### ISSUE THREAD

**Issue by rpitonak** [packit-service/packit-service#132]
```{'jobs': {'pull_request_action': {'success': False, 'details': {'msg': 'No Handler for JobTriggerType.comment'}}}, 'event': {'trigger': 'JobTriggerType.comment', 'action': 'PullRequestCommentAction.created', 'pr_id': 14, 'base_repo_namespace': 'packit-service', 'base_repo_name': 'hello-world', 'base_ref': None, 'commit_sha': '08bfc38f15082bdf9ba964c3bbd04878666d1d56', 'target_repo': 'packit-service/hello-world', 'https_url': 'https://github.com/packit-service/hello-world' , 'github_login': 'rpitonak', 'comment': '/packit copr-build'}, 'trigger': 'JobTriggerType.comment'}```

**Comment by phracek** [comment]
The message is used https://github.com/packit-service/packit-service/blob/master/packit_service/worker/copr_build.py#L193 which is weird. I would prefer to use something like:
`Copr build failed {build_state). Copr build_id is {build_id}`

Later on we can find what's going on.
