### ISSUE TITLE
Design POD initialization and run_actions for a specific package

### ISSUE THREAD

**Issue by phracek** [packit-service/packit-service#14]
I am trying to figure out how to start a POD and how to run `actions` defined in package `packit.yaml` configuration file.

My idea first is to check if `self.package_config` contains any action( https://github.com/packit-service/packit-service/blob/master/packit_service/worker/jobs.py#L396)
If so, then instantiate sandcastle object (https://github.com/packit-service/sandcastle) and pass it into PackitAPI constructor. By default `sandcastle_object` is None.

But what I have in my mind is how to run actions.

1. First one is to execute function `sync_release` which calls all actions. It raises in my mind, how we will propagate into `packit-service` return code, JSON output of POD success or failure. Does `packit-service` need information about POD success?
2. The second approach would be to pull out to PackitAPI function called `run_actions` with specific actions like `Action.pre_sync` before `sync_release` and `Action.post_sync` after `sync_release`. Does this make sense?

**Comment by TomasTomecek** [comment]
> My idea first is to check if `self.package_config` contains any action( https://github.com/packit-service/packit-service/blob/master/packit_service/worker/jobs.py#L396)
> If so, then instantiate sandcastle object (https://github.com/packit-service/sandcastle) and pass it into PackitAPI constructor. By default `sandcastle_object` is None.

I reworked this in packit so that nothing needs to be passed and everything is handled within packit, all it needs is changes in the config file. Still WIP in my laptop since it's not done, hopefully tomorrow.

>     1. First one is to execute function `sync_release` which calls all actions. It raises in my mind, how we will propagate into `packit-service` return code, JSON output of POD success or failure. Does `packit-service` need information about POD success?

raise an exc in case of failure, otherwise just continue the execution

>     2. The second approach would be to pull out to PackitAPI function called `run_actions` with specific actions like `Action.pre_sync` before `sync_release` and `Action.post_sync` after `sync_release`. Does this make sense?

Honestly, I'd say that we don't need any code in packit-service to handle sandcastle. The only change would be in deployment to populate the config file.

**Comment by TomasTomecek** [comment]
Fixed by #16 afaik
