### ISSUE TITLE
Packit service does not clear test flags on "/packit copr-build"

### ISSUE THREAD

**Issue by thrix** [packit-service/packit-service#140]
Seems packit does not clear test flags on ```/packit copr-build``` I still see the old results until a new copr build was built.

**Comment by thrix** [comment]
An example:
![not-cleared](https://user-images.githubusercontent.com/633969/65189088-4af0d400-da70-11e9-9a3f-fa6c03cdccaf.png)

**Comment by TomasTomecek** [comment]
so the request is to clear all testing-farm check statuses when

* there is a new push to the PR
* or someone performs `/packit copr-build`
* or someone performs `/packit test` (soon, TBD)

makes sense to me

**Comment by dhodovsk** [comment]
Requires https://github.com/packit-service/ogr/issues/133

**Comment by dhodovsk** [comment]
It seems that at the moment, there is no possibility to actually clear the commit statuses (aside from the push):
 * https://github.community/t5/GitHub-API-Development-and/Delete-or-cancel-commit-status/td-p/17928
 * https://developer.github.com/v3/repos/statuses/

But we can for the situations:
> * there is a new push to the PR

For new pushes to pull request, the checks are cleared automatically in github.

> * or someone performs `/packit copr-build`
> * or someone performs `/packit test` (soon, TBD)

For the `/packit copr-build` (and potentially `/packit test`) we can switch it back to pending as testing farm does.

> * or timeout on our side? (Edit: Rado)

On timeouts on our side, we can deal with it here: https://github.com/packit-service/packit-service/issues/225

**Comment by lachmanfrantisek** [comment]
> For new pushes to pull request, the checks are cleared automatically in github.

Not always. (I am not sure, but Github probably runs some magic to determine if it is needed.)

**Comment by dhodovsk** [comment]
> > For new pushes to pull request, the checks are cleared automatically in github.
> 
> Not always. (I am not sure, but Github probably runs some magic to determine if it is needed.)

True, it seems only for pushes that change the HEAD hash. (Assuming the pull request status is the status of the last commit on the PR) https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/about-status-checks

**Comment by dhodovsk** [comment]
Looking at the code, [run_copr_buld](https://github.com/packit-service/packit-service/blob/master/packit_service/worker/copr_build.py#L130) should report pending status on every new copr build. In our hello-world repository, it also works correctly now. Could have this been a packit service outage or maybe unreported error that is [now fixed](https://github.com/packit-service/packit-service/commit/f1251995a53a9af2a571554f958a6d65ae2dc75f)?

@thrix are you still able to reproduce this?

**Comment by lachmanfrantisek** [comment]
I think we don't fix the problem but response much sooner with the pending state. I hope it is not a big problem now.

**Comment by dhodovsk** [comment]
Oh, I totally misunderstood. We want to clear the packit test result, not only the copr build, sorry about that
