### ISSUE TITLE
commit check status can't exceed 140 chars

### ISSUE THREAD

**Issue by TomasTomecek** [packit-service/packit-service#141]
Let's finally set this in the method which performs the api call to trim the string to 140 chars.
```
[2019-09-18 08:43:10,000: ERROR/ForkPoolWorker-1] Task task.steve_jobs.process_message[d5272b85-b3b4-4246-8284-59bd4e632654] raised unexpected: GithubException(422, {'messag
e': 'Validation Failed', 'errors': [{'resource': 'Status', 'code': 'custom', 'field': 'description', 'message': 'description is too long (maximum is 140 characters)'}], 'doc
umentation_url': 'https://developer.github.com/v3/repos/statuses/#create-a-status'})
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/celery/app/trace.py", line 382, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/celery/app/trace.py", line 641, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/packit_service/worker/tasks.py", line 42, in process_message
    return SteveJobs().process_message(event=event, topic=topic)
  File "/usr/local/lib/python3.7/site-packages/packit_service/worker/jobs.py", line 242, in process_message
    jobs_results[JobType.report_test_results.value] = handler.run()
  File "/usr/local/lib/python3.7/site-packages/packit_service/worker/testing_farm_handlers.py", line 88, in run
    + self.event.copr_chroot,
  File "/usr/local/lib/python3.7/site-packages/packit_service/worker/handler.py", line 111, in report
    self.commit_sha, state, url, description, check_name
  File "/usr/local/lib/python3.7/site-packages/ogr/read_only.py", line 68, in readonly_func
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/ogr/services/github.py", line 630, in set_commit_status
    github_commit.create_status(state, target_url, description, context)
  File "/usr/lib/python3.7/site-packages/github/Commit.py", line 189, in create_status
    input=post_parameters
  File "/usr/lib/python3.7/site-packages/github/Requester.py", line 276, in requestJsonAndCheck
    return self.__check(*self.requestJson(verb, url, parameters, headers, input, self.__customConnection(url)))
  File "/usr/lib/python3.7/site-packages/github/Requester.py", line 287, in __check
    raise self.__createException(status, responseHeaders, output)
github.GithubException.GithubException: 422 {'message': 'Validation Failed', 'errors': [{'resource': 'Status', 'code': 'custom', 'field': 'description', 'message': 'descript
ion is too long (maximum is 140 characters)'}], 'documentation_url': 'https://developer.github.com/v3/repos/statuses/#create-a-status'}
```

**Comment by lachmanfrantisek** [comment]
Related to this one in OGR: https://github.com/packit-service/ogr/issues/143

What behaviour do we want in OGR? trim x exception

**Comment by TomasTomecek** [comment]
we already get an exception now, which is bad, we should trim it, so something like:
```
github_commit.create_status(state, target_url, description[:140], context)
```

**Comment by lachmanfrantisek** [comment]
> we already get an exception now, which is bad, we should trim it, so something like:

I do not like Github exception either but I am not 100% sure if the trimming is correct behaviour.

(If I set the status to some text and it goes well, I expect that the text in the status is not changed.)

What about some `trim=True` argument?

**Comment by TomasTomecek** [comment]
> > we already get an exception now, which is bad, we should trim it, so something like:
> 
> I do not like Github exception either but I am not 100% sure if the trimming is correct behaviour.
> 
> (If I set the status to some text and it goes well, I expect that the text in the status is not changed.)
> 
> What about some `trim=True` argument?

Okay, let me give you my view of this problem: I don't want to see tracebacks in production, that is my requirement. However we implement it (forcible trim, configurable trim, something like), I don't care to be honest. What I care is functional software and that we prevent tracebacks like this in the future.

**Comment by lachmanfrantisek** [comment]
> I don't want to see tracebacks in production, that is my requirement.

This should solve your problem..;)

```python
try:
    all()
except Exception:
    pass
```

Then the solutions are as follows:
1. .
    - raise an OGR exception in OGR. (and document that behaviour)
    - trim that in service
2. .
    - add `trim=False` to OGR method
    - trim that in service
3. .
    - add `trim=True` to OGR method
    - no changes needed in service

Personaly, I do not like silently changing the input of methods.

**Comment by TomasTomecek** [comment]
>     1. .
>        
>        * raise an OGR exception in OGR. (and document that behaviour)
>        * trim that in service
> 
>     2. .
>        
>        * add `trim=False` to OGR method
>        * trim that in service

1 or 2 sounds good, then we both be happy; we can do 1 since that's the one you seem to like the most

> Personaly, I do not like silently changing the input of methods.

and I don't like tracebacks in prod

**Comment by lachmanfrantisek** [comment]
@lbarcziova fixed that in OGR in https://github.com/packit-service/ogr/pull/210

Now we only need to use `trim=True` when using that method.
