### ISSUE TITLE
Loading config in the config.py

### ISSUE THREAD

**Issue by lachmanfrantisek** [packit-service/packit-service#153]
Is there some strong reason why we are running code in the `packit_service.config`?

https://github.com/packit-service/packit-service/blob/5ef755e61c7a3274041a05b073e85b8fed010730/packit_service/config.py#L137

What about using some function for that instead?

In this case, each time we need to import something from the file, it tries to load my user config and if it fails to validate, the code will raise an Exception. (Especially, I cannot run unit tests without having valid config.)

**Comment by lachmanfrantisek** [comment]
Short-term fix:
```python
from lazy_object_proxy import Proxy
service_config = Proxy(ServiceConfig.get_service_config)
```

**Comment by rpitonak** [comment]
I can't remember the reason so feel free to change it.
