### ISSUE TITLE
RFE: packit service could contain some scheduler for repetitive task (creating new PR daily)

### ISSUE THREAD

**Issue by jscotka** [packit-service/packit-service#158]
packit service could provide via  packit.yaml configuration some way, how to say that you would like to create some PR to project in some cron format.

Use story:
 -  when using ``requre`` or another depencencies what may change, it could happen, that something breaks without any code change, so that when someone creates new PR, eg. test automation, or tool itself is broken.
 - **Solution:** packit service is able to create PR to this project each day (week) and project contains some CI and in case tests in PR fails could raise issue to project, or this PR would have some labels, to be very important in the project.

This is probably feature what is not covered by any CI system, at least on github. becayse they are event based, and packit-service could provide trigger/reporting for these event based CIs

**Comment by lachmanfrantisek** [comment]
Gitlab has feature for scheduled tasks. What about using some Gitlab instance for this?

**Comment by TomasTomecek** [comment]
> packit service could provide via packit.yaml configuration some way, how to say that you would like to create some PR to project in some cron format.

some way, some PR, some cron format

I'll say this right away: no.

How does this RFE align with our goals and roadmap? Packit service is not meant to be a dumpster bin for all the RFEs imaginable.

> 
> Use story:
> 
>     * when using `requre` or another depencencies what may change, it could happen, that something breaks without any code change, so that when someone creates new PR, eg. test automation, or tool itself is broken.
> 
>     * **Solution:** packit service is able to create PR to this project each day (week) and project contains some CI and in case tests in PR fails could raise issue to project, or this PR would have some labels, to be very important in the project.
> 
> 
> This is probably feature what is not covered by any CI system, at least on github. becayse they are event based, and packit-service could provide trigger/reporting for these event based CIs

GitHub covers this as well: https://github.com/features/actions

The user story is good and it makes sense, but definitely not for packit-service, hence I'm closing. I suggest creating a jira card for this.
