### ISSUE TITLE
Deploy every change to stg automatically.

### ISSUE THREAD

**Issue by rpitonak** [packit-service/packit-service#169]
We can utilize the zuul gating for this since we have staging secrets there.

Steps (from the top of my mind):

- [ ] encrypt new secrets for stg, since they have changed recently. Guide is [here](https://github.com/packit-service/deployment/#zuul) (update might be needed).
- [ ] Add openshift token to zuul CI. (we may want to have a "special" service account for this)
- [ ] add a new job to zuul gating (`DEPLOYMENT=stg make deploy`)
- [ ] Update [Contribution guide](/CONTRUBUTING.md) with the statement that we merging all PRs using zuul label `mergeit`

**Comment by jpopelka** [comment]
Or we can do that from the other side (Openshift).
I hope https://github.com/packit-service/deployment/pull/31 (WIP now) should mostly do this.

**Comment by jpopelka** [comment]
Done in https://github.com/packit-service/deployment/pull/31
