### ISSUE TITLE
implement retention policy for copr builds

### ISSUE THREAD

**Issue by TomasTomecek** [packit-service/packit-service#17]
* [ ] inactivity for X days: comment on the PR and then remove the builds
* [ ] remove builds once the PR is merged
* [ ] ~~remove old builds when a PR changes~~ copr does this already
* [x] for all the projects we already have, set the expiration to 30 days

**Comment by praiskup** [comment]
This is pretty easily maintainable from the packit side (API should be available);  if you wanted, you can use "temporary" projects feature in copr (copr will delete the project after specified time), there won't be any feedback to github/packit once the delete action happens.

**Comment by praiskup** [comment]
IOW, all the three points are equal to `copr delete <PROJECT>` action.

**Comment by dhodovsk** [comment]
For clarification is this OK, or can it be done better?: 

> * [ ]  inactivity for X days: comment on the PR and then remove the builds

 - create time specific task (a.k.a cron job) and it's handler, that would daily poll all pull-requests found in metrics using this query:
`all PR's from successful copr build task minus all PR's from successful copr build delete task`. If the last comment was X days ago, delete the build.

> * [ ]  remove builds once the PR is merged

- react on [pullrequest webhooks](https://developer.github.com/v3/activity/events/types/#pullrequestevent) with `action = closed or merged` using new job type - `copr_build_delete`

> * [ ]  for all the projects we already have, set the expiration to 30 days
- does this mean also add an expiration date to newly created projects? https://github.com/packit-service/packit/blob/master/packit/api.py#L541 or just for the already existing

**Comment by TomasTomecek** [comment]
> For clarification is this OK, or can it be done better?:
> 
> > * [ ]   inactivity for X days: comment on the PR and then remove the builds
> 
>     * create time specific task (a.k.a cron job) and it's handler, that would daily poll all pull-requests found in metrics using this query:
>       `all PR's from successful copr build task minus all PR's from successful copr build delete task`. If the last comment was X days ago, delete the build.

sounds good, but on the other hand: it seems pretty complicated and fragile; I'd personally vote not to implement this and probably just document that builds are stored for 30 days and then they are removed - I'm also thinking that not many PRs would utilize this feature - even in our case we manage to process 9/10 PRs "on time"

> > * [ ]   remove builds once the PR is merged
> 
>     * react on [pullrequest webhooks](https://developer.github.com/v3/activity/events/types/#pullrequestevent) with `action = closed or merged` using new job type - `copr_build_delete`

+1

> > * [ ]   for all the projects we already have, set the expiration to 30 days
> 
>     * does this mean also add an expiration date to newly created projects? https://github.com/packit-service/packit/blob/master/packit/api.py#L541 or just for the already existing

yup: old and new

**Comment by TomasTomecek** [comment]
all of these get solved by the last item: remove builds after X days so I'm marking this as done - sadly we don't have capacity to implement points 1 and 2

**Comment by TomasTomecek** [comment]
Fixed by https://github.com/packit-service/packit/pull/515
