### ISSUE TITLE
Drop Task model (celery-tasks hash in our redis db)

### ISSUE THREAD

**Issue by jpopelka** [packit-service/packit-service#173]
The [Task model](https://github.com/packit-service/packit-service/blob/master/packit_service/service/models.py#L112) stores all incoming events into `celery-tasks` hash.

It is:

A) **useless**
There's IMHO no useful info we can't get from what Celery automatically stores in the tasks metadata. Example:
This is what [we store](https://github.com/packit-service/packit-service/blob/master/packit_service/worker/tasks.py#L46) about a task/event in the `celery-tasks` hash:
```python
{'identifier': '164ee1e2-5b9d-4edd-a195-44779eb98434',
 'metadata': {'user': 'packit',
  'copr': 'rpm-software-management-dnf-1495',
  'owner': 'packit',
  'pkg': 'dnf',
  'build': 1059898,
  'chroot': 'fedora-29-x86_64',
  'version': '4.2.11.45.g4c5434d9-1.fc30',
  'status': 3,
  'ip': '172.25.81.133',
  'who': 'backend.worker-12730-PC',
  'pid': 12446,
  'what': 'build start: user:packit copr:rpm-software-management-dnf-1495 pkg:dnf build:1059898 ip:172.25.81.133 pid:12446',
  'topic': 'org.fedoraproject.prod.copr.build.start'},
 'date_created': '2019-10-16T10:32:30.392790'}
```
and this is what's stored by Celery (when we [return an Event subclass object from process_message()](https://github.com/packit-service/packit-service/blob/master/packit_service/worker/jobs.py#L281)):
```python
{'status': 'SUCCESS',
 'result': {'jobs': {},
  'event': {'trigger': 'JobTriggerType.commit',
   'project_url': None,
   'topic': 'FedmsgTopic.copr_build_started',
   'build_id': 1059898,
   'chroot': 'fedora-29-x86_64',
   'status': 3,
   'owner': 'packit',
   'project_name': 'rpm-software-management-dnf-1495',
   'base_repo_name': '',
   'base_repo_namespace': '',
   'pr_id': 0,
   'ref': '',
   'commit_sha': '',
   'build': None}},
 'traceback': None,
 'children': [],
 'task_id': '164ee1e2-5b9d-4edd-a195-44779eb98434'}
```
The difference between those two is that the first one stores the event as it comes in, while the second stores it after [parsing it](https://github.com/packit-service/packit-service/blob/master/packit_service/worker/parser.py#L59) to Event subclass object ([CoprBuildEvent](https://github.com/packit-service/packit-service/blob/master/packit_service/service/events.py#L395) in this case).
The only info which currently is not in the second is the `'date_created'`, but that's two lines in the [Event class](https://github.com/packit-service/packit-service/blob/master/packit_service/service/events.py#L83).

B) **memory hog**
redis-cli@prod$ HLEN celery-tasks _(number of entries)_
54784
$ MEMORY USAGE celery-tasks
185023945 (i.e. 185MB - in memory)
When I try to list it in `redis-commander`, the browser eats all memory and sends my computer to oblivion.

**Comment by TomasTomecek** [comment]
+1

What do you suggest doing?

**Comment by TomasTomecek** [comment]
yeah, okay

**Comment by jpopelka** [comment]
Just did `DEL celery-tasks` on `prod` and the memory consumption of `redis` dropped from 544MB to 200MB.
