### ISSUE TITLE
give fedora-messaging another try

### ISSUE THREAD

**Issue by TomasTomecek** [packit-service/packit-service#18]
https://github.com/fedora-infra/fedora-messaging/issues/111#issuecomment-480434408

**Comment by lachmanfrantisek** [comment]
@TomasTomecek Any updates?

**Comment by TomasTomecek** [comment]
Current status
* we need credentials in order to be able to submit to fedora-messaging bus
* there is a public broker where anyone can consume events

Do we want a dedicated topic to post our own events?

**Comment by TomasTomecek** [comment]
@rpitonak Fixed by #142?

**Comment by rpitonak** [comment]
> @rpitonak Fixed by #142?

Yes, that PR should resolve this.
