### ISSUE TITLE
Packit shows success when rawhide copr build failed

### ISSUE THREAD

**Issue by psss** [packit-service/packit-service#201]
See the following pull request:

* https://github.com/psss/tmt/pull/26

And corresponding copr build:

* https://copr.fedorainfracloud.org/coprs/packit/psss-tmt-26/build/1085419/

Rawhide build failed but packit reports `RPMs were built successfully`.

**Comment by TomasTomecek** [comment]
We should raise this one with copr team since we just forward the status from the copr api to the github status check.

**Comment by TomasTomecek** [comment]
I'd this got broken by the recent change of getting the results from fedmsg: we keep updating the status for every build, which means that if a build fails, the status is failed, if another build passes, the status is suddenly passed.

The change which should happen here is that if any build failed, we should no longer set status to passed, or, don't update the status unless all builds are done (we should indicate this also in the status message).

**Comment by dhodovsk** [comment]
Related to: https://github.com/packit-service/packit-service/issues/224

**Comment by TomasTomecek** [comment]
AI: create one status line for every chroot, instead of having a single status for all

**Comment by psss** [comment]
Thanks for the fix!
