### ISSUE TITLE
ansible ain't no bash

### ISSUE THREAD

**Issue by jpopelka** [packit-service/packit-service#205]
- [files/check-inside-openshift.yaml](https://github.com/packit-service/packit-service/blob/master/files/check-inside-openshift.yaml)

**Comment by rpitonak** [comment]
I am working on re-writing this using [k8s_module](https://docs.ansible.com/ansible/latest/modules/k8s_module.html) and [k8s_info](https://docs.ansible.com/ansible/2.9/modules/k8s_info_module.html).
