### ISSUE TITLE
All entries in redis/github_installation have status waiting

### ISSUE THREAD

**Issue by jpopelka** [packit-service/packit-service#216]
Ok, so this actually isn't that straightforward.
There's a lot of redundancy (to be removed) between `github_installation` and `whitelist` tables/hashes.
Both of them store the [InstallationEvent](https://github.com/packit-service/packit-service/blob/master/packit_service/service/events.py#L289)
- into `github_installation` [here](https://github.com/packit-service/packit-service/blob/master/packit_service/worker/github_handlers.py#L141)
- into `whitelist` [here](https://github.com/packit-service/packit-service/blob/master/packit_service/worker/whitelist.py#L103) and [here](https://github.com/packit-service/packit-service/blob/master/packit_service/worker/whitelist.py#L128)

I think we want the whole `InstallationEvent` (probably without the `status`) only in `github_installation` and `whitelist` would store just the `account_login`: `status`.

**Comment by TomasTomecek** [comment]
this is gonna solve itself after #459

**Comment by jpopelka** [comment]
@lbarcziova could you take a look at this
once you are done with (or while you're working on)
the Redis -> Postgres migration?

**Comment by lbarcziova** [comment]
The new models in psql store:
Whitelist -> account, status
Installation -> InstallationEvent

**Comment by jpopelka** [comment]
@lbarcziova we can close this now, can't we?

**Comment by lbarcziova** [comment]
@jpopelka yes
