### ISSUE TITLE
Dedicated workers for packit in Copr

### ISSUE THREAD

**Issue by thrix** [packit-service/packit-service#218]
As more people are onboarding COPR's performance becomes a PITA. Sometimes builds wait up to several hours. CI system needs to have a quick feedback, othewise people will be using something else to do the testing instead of Packit/Testing Farm.

We need to have a conversation with @xsuchy and @praiskup about the topic. The next milestone is Devconf 2020, where we will have a demo and people should not be blocked on this and be able to do the lab quickly.

**Comment by xsuchy** [comment]
We are going to use AWS for builder where we can create big boosters. This was blocked by past 3 months by fedora-infra but has been unblocked last week. You should see some change pretty soon.

**Comment by thrix** [comment]
@xsuchy that is pretty cool, thanks for the info. Will leave this open until we have that and we can re-evaluate if needed.

**Comment by thrix** [comment]
Ups, clicked wrong button :D

**Comment by TomasTomecek** [comment]
We just talked about this and our plan is to wait for the Copr team to utilize AWS and then see if the build times get better. If not, then we'd figure out how we want to resolve the situation.

**Comment by xsuchy** [comment]
We already use the AWS for builders (intels and aarch64). There is enough workers now. If you feel the need for more (e.g. there will be some workshop planned ahead) then let us know. 
In the future, we plan to even handle those sudden peaks automatically.

I think you can close this now.

**Comment by lachmanfrantisek** [comment]
@xsuchy thanks for the info! Let's close this.
