### ISSUE TITLE
lazy badges.fedoraproject.org/user/{user}/json

### ISSUE THREAD

**Issue by jpopelka** [packit-service/packit-service#220]
We query https://badges.fedoraproject.org/user/{user}/json in [Whitelist._is_packager()](https://github.com/packit-service/packit-service/blob/master/packit_service/worker/whitelist.py#L56) to check whether a user is Fedora packager.

It takes from 5s (for nonexisting user) to over a minute (for users with lots of badges).

```bash
$ time curl https://badges.fedoraproject.org/user/foobarbaz/json
real	0m5.311s
$ time curl https://badges.fedoraproject.org/user/jpopelka/json
real	1m7.064s
```

Wouldn't [Koji API](https://docs.pagure.org/koji/using_the_koji_build_system/#koji-xmlrpc-api) be faster?
```bash
$ koji list-api
getUser(userInfo=None, strict=False)
  description: Return information about a user.

    userInfo may be either a str (Kerberos principal or name) or an int (user id).

    A map will be returned with the following keys:
      id: user id
      name: user name
      status: user status (int), may be null
      usertype: user type (int), 0 person, 1 for host, may be null
      krb_principal: the user's Kerberos principal
```

EDIT: Hint: use [xmlrpc.client](https://docs.python.org/3/library/xmlrpc.client.html#module-xmlrpc.client)

**Comment by csomh** [comment]
@jpopelka, was using fas.fedoraproject.org already discussed as a solution for this?

My thought process is that FAS sounds like a central place to manage users in Fedora space, so it might have more reliable answers to the question whether a user is a Fedora packager or not. I might be wrong with this, but I assume that Koji uses FAS under the hood somewhere.

Logging in to my FAS account I can see that there is a *packager* group. I have no clue about FAS API though, but that can be probably looked up.

**Comment by jpopelka** [comment]
You're right Hunor, FAS would be the best place to take the info from.
I, however, don't see an easy way how to do that. If you do, I'd be happy to see it implemented.
There was no discussion as far as I remember (@rpitonak who implemented the whitelist is on PTO), Koji has been just my suggestion.

**Comment by csomh** [comment]
Very true, Jirka, doing this would mean more change than simply calling Koji.

[python-fedora] seems to be the way to interact with FAS, but requests need HTTP auth (from what I can tell, this is the only way). 

[`fas_user`] is already in the packit configs. To use [`fedora.client.fas2.AccountSystem`], the password for the `fas_user` should be included in the configs. `packit_service.config.ServiceConfig` seems to be the right place. The credentials could be passed to the `Whitelist` constructor in `GithubAppInstallationHandler.run()`, to be used by `_is_packager()`.

What do you think of the above?

[python-fedora]: https://github.com/fedora-infra/python-fedora
[`fas_user`]: https://github.com/packit-service/packit/blob/master/packit/config/config.py#L52
[`fedora.client.fas2.AccountSystem`]: https://github.com/fedora-infra/python-fedora/blob/develop/fedora/client/fas2.py#L73

**Comment by TomasTomecek** [comment]
> Very true, Jirka, doing this would mean more change than simply calling Koji.
> 
> [python-fedora](https://github.com/fedora-infra/python-fedora) seems to be the way to interact with FAS, but requests need HTTP auth (from what I can tell, this is the only way).

That shouldn't be a problem: packit has a FAS account and a keytab.

> [`fas_user`](https://github.com/packit-service/packit/blob/master/packit/config/config.py#L52) is already in the packit configs. To use [`fedora.client.fas2.AccountSystem`](https://github.com/fedora-infra/python-fedora/blob/develop/fedora/client/fas2.py#L73), the password for the `fas_user` should be included in the configs. `packit_service.config.ServiceConfig` seems to be the right place. The credentials could be passed to the `Whitelist` constructor in `GithubAppInstallationHandler.run()`, to be used by `_is_packager()`.
> 
> What do you think of the above?

oh, so no kerberos, that's fine; sounds good to auth via password
