### ISSUE TITLE
fedora-messaging schema issues

### ISSUE THREAD

**Issue by jpopelka** [packit-service/packit-service#221]
We're currently not updating copr build checks in PRs. This is all I see in fedmsg pod logs:

```
[WARNING fedora_messaging.message] The schema "copr.build.start" is not in the schema registry! Either install the package with its schema definition or define a schema. Falling back to the default schema...
[INFO fedora_messaging._session] Consuming message from topic "org.fedoraproject.prod.copr.build.start" (id 6875ed24-b4db-4824-ad34-4d08ac4bf881)
[WARNING fedora_messaging.message] The schema "copr.build.end" is not in the schema registry! Either install the package with its schema definition or define a schema. Falling back to the default schema...
[INFO fedora_messaging._session] Consuming message from topic "org.fedoraproject.prod.copr.build.end" (id ed16a560-8fbf-45be-96af-7dadde671688)
```

**Comment by dhodovsk** [comment]
It seems to work again https://github.com/packit-service/packit/pull/601 :)

**Comment by TomasTomecek** [comment]
So the problem was not in our code - let me create an issue to improve usability when such thing happens in future again.

**Comment by dhodovsk** [comment]
How the we know the problem was not on our side?

**Comment by jpopelka** [comment]
> It seems to work again

Looking at both workers logs; the outage was from
`2019-11-07 11:10` to `2019-11-11 22:53`

> How do we know the problem was not on our side?

We (or at least I) don't know. 
There are no timestamps in the `fedmsg` pod logs, so I don't know what was happening in the above timeframe, but I don't see any abnormalities in the logs, so I guess there were just no messages comming from the bus.

**Comment by dhodovsk** [comment]
According to datagrepper, the messages were sent.

For example these are the data from 2019-11-09 01:00 to 2019-11-09-12:00 UTC https://apps.fedoraproject.org/datagrepper/raw?topic=org.fedoraproject.prod.copr.build.end&start=1573261200&end=1573300800

**Comment by jpopelka** [comment]
Then the problem was on our side.

**Comment by jpopelka** [comment]
> [WARNING fedora_messaging.message] The schema "copr.build.start" is not in the schema registry!

#227

**Comment by jpopelka** [comment]
> There are no timestamps in the `fedmsg` pod logs

#229

**Comment by TomasTomecek** [comment]
but it started to work w/o us doing anything - hence I assumed the problem was not on our side
