### ISSUE TITLE
inform user when there are problems with packit.yaml

### ISSUE THREAD

**Issue by TomasTomecek** [packit-service/packit-service#222]
For PRs, set check status when packit.yaml is invalid. Print all warnings in log.

For releases, create new issue when packit.yaml is invalid.

----

edit: relevant example:

- sentry: https://sentry.io/organizations/red-hat-0p/issues/1440247249/?project=1767823&query=is%3Aunresolved
- Related PR: https://github.com/packit-service/packit/pull/660

**Comment by lachmanfrantisek** [comment]
Looks still important to me.
