### ISSUE TITLE
inform user when there are infra problems

### ISSUE THREAD

**Issue by TomasTomecek** [packit-service/packit-service#225]
The problem:
Underlying infrastructure problems make us look bad - e.g. a build is in pending state for hours while something is wrong with services we relay on (copr queue full, fedora-messaging outage, something else) - even though it's not our problem, we are the bad ones.

Possible solution:
* watchdog-like task that babysits the build and if not done in time (1 hour), gives not to user (and us ideally, via sentry e.g.)

**Comment by dhodovsk** [comment]
From a quick team brainstorm:
 * For every task we can schedule a validation task that is triggered after with reasonalbe postpone (e.g. 2 hours after copr_build is triggered) and checks whether the build is in the expected state.

**Comment by lachmanfrantisek** [comment]
Still relevant.

**Comment by TomasTomecek** [comment]
hm, this is very close to #25
