### ISSUE TITLE
tests requre data regeneration

### ISSUE THREAD

**Issue by jpopelka** [packit-service/packit-service#236]
Instructions say to run `make check-inside-openshift PATH_TO_SECRETS=./secrets` but it doesn't say how to specify to which cluster/project does it deploy to.

I see [deployment specified here](https://github.com/packit-service/packit-service/blob/master/files/test-in-openshift-secrets.yaml#L29) hardcoded to `stg`.

After some digging, I found out that I have to first `oc login https://127.0.0.1:8443`.
Also, I don't see the `PATH_TO_SECRETS` used anywhere.

**Comment by jpopelka** [comment]
And when I was finally able to run it on oc cluster up: https://paste.fedoraproject.org/paste/GuhD1aMJzFX~31LMAwGoaA

**Comment by rpitonak** [comment]
> And when I was finally able to run it on oc cluster up: https://paste.fedoraproject.org/paste/GuhD1aMJzFX~31LMAwGoaA

A possible workaround is to create directories on host first:
```
mkdir -p tests_requre/test_data/test_fedpkg
mkdir tests_requre/test_data/test_copr
```
