### ISSUE TITLE
RFE: fedora-current-x86_64 alias

### ISSUE THREAD

**Issue by yarda** [packit-service/packit-service#241]
We don't want to edit the yaml file each time new Fedora is released or old Fedora gets 
unsupported. Instead of writing:
```
    targets:
    - fedora-30-x86_64
    - fedora-31-x86_64
    - fedora-rawhide-x86_64
```
could there be just an alias, e.g.:
```
    targets:
    - fedora-current-x86_64
```
Or some different syntax to expand to all currently supported Fedora's?

**Comment by rpitonak** [comment]
Hi @yarda! Thank you for opening the issue. 

This is actually a good point and we have received similar feedback already. I think this might be a dupe of https://github.com/packit-service/packit/issues/540.

**Comment by yarda** [comment]
@rpitonak yes, it's dupe, I didn't find it somehow, so closing.
