### ISSUE TITLE
keep tasks in queue when a dependant service is down

### ISSUE THREAD

**Issue by TomasTomecek** [packit-service/packit-service#25]
Let's say COPR is down and all the API calls are failing: if such a thing happens we should keep tasks in a queue and process them once we're able to succeed.

Dominika says celery has autoretry which could solve this. https://www.distributedpython.com/2018/09/04/error-handling-retry/

**Comment by jpopelka** [comment]
Shouldn't be that hard with celery-autoretry, marking as good-first-issue.

**Comment by TomasTomecek** [comment]
Actually, this could even be extended to letting the user know that some infrastructure is slow or borked and that's the reason packit is trying to build the RPM for 5 hours.

**Comment by TomasTomecek** [comment]
I'd even extend this to not rely on fedora-messaging at all: once we submit a build, we have a new celery task, which would check the build periodically so that we wouldn't need to count on f-m.

**Comment by TomasTomecek** [comment]
If possible, we shouldn't spam the PR with identical comments - we should only comment once.

Franta says that we should post only a single comment after we try X times and fail to proceed.
