### ISSUE TITLE
improve redis server handling in tests

### ISSUE THREAD

**Issue by jscotka** [packit-service/packit-service#264]
openshift requre tests uses running redis server, it is hardcoded in bash script running tests with ``sleep 5`` to ensure that server is running.
https://github.com/packit-service/packit-service/blob/master/files/run_tests.sh#L12

Would be better to replace it by some opeshift magic, e.g. run redis server is dedicated pod, and tests will use it.

**Comment by jpopelka** [comment]
https://github.com/packit-service/deployment/blob/master/openshift/redis.yml

we just don't need the `PersistentVolumeClaim`

**Comment by TomasTomecek** [comment]
but the PVC should also not cause any harm, right?
