### ISSUE TITLE
{'jobs': {'copr_build_started': None}, 'event': ...}

### ISSUE THREAD

**Issue by jpopelka** [packit-service/packit-service#273]
I thought this had been fixed since #197 but it keeps occurring.

* https://sentry.io/organizations/red-hat-0p/issues/1369081657
* https://sentry.io/organizations/red-hat-0p/issues/1369205660

**Comment by TomasTomecek** [comment]
maybe copr sends us some funky messages?

**Comment by jpopelka** [comment]
ok, let's blame Copr, closing  ... (kidding)

**Comment by TomasTomecek** [comment]
but honestly I don't even understand what the error is, the only problem seems to be: `failed to reach url with copr chroot build result.`

**Comment by TomasTomecek** [comment]
AI: change the log level to info and don't store it in sentry - this is expected behaviour, the file does not exist yet on copr side

**Comment by TomasTomecek** [comment]
fixed
