### ISSUE TITLE
Testing-farm in the default jobs

### ISSUE THREAD

**Issue by lachmanfrantisek** [packit-service/packit-service#281]
background: We want to simlify the config file as much as possible and want to have testing-farm turned on by default.

- Which chroots will by used by default? `fedora-stable` (since rawhide is usually broken)
- What needs to be done on the packit side?
- What needs to be done on the testing-farm side? (@thrix , @psss )
- What about package without fmf setup?
    - Leave everything to testing-farm: no `.fmf` => empty test suite => return "Installation successful`
    - Try to generate `.fmf` with some basic `ci.fmf` on our side. (Not sure, how we can send it to testing farm.)

**Comment by thrix** [comment]
So is the idea that by default we run artifact installation if not other tests added? Stef also wanted to have a no-fmf way how people can add a test script directly into packit config without the need to specify any FMF file.

**Comment by thrix** [comment]
Anyay, in the current state of things, we did not expect to have an install only test scenario. If there is no .fmf nothing will be run and an error will be returned.

Better to think about this sooner the later. Of course, we can implement it as we want :) @psss what do you think?

**Comment by psss** [comment]
Running tests by default to simplify config makes sense to me. But I'd say only if there is at least one plan defined. The following `tmt` command can be used to check if there are any plans available:

    tmt plans ls

If there is no plan defined I would suggest to do nothing (from the testing perspective).

**Comment by lachmanfrantisek** [comment]
Most of the projects will not have fmf defined at all.
- We probably don't want to show error states for those projects.
    - => Show error to force them to setup fmf.
    - => Do not show anything.
    - => Show `installation` successfull. The success/failure of  the installation of the package from the copr repo can be useful.

**Comment by lachmanfrantisek** [comment]
Since we have a default behaviour on the testing-farm side, we can probably turn on the tests by default (=when people don't specify the `jobs` section in the config).

Do we want to have both `copr-build` and `tests`. Or only the `tests` status for each chroot?

**Comment by thrix** [comment]
I would say only tests, but as you wish, I am ready for the load :)

**Comment by lachmanfrantisek** [comment]
> I would say only tests, but as you wish, I am ready for the load :)

Just to make it 100% clear, the build and tests will be run in all cases. It's only about UX -- if we want to have both `build-???` and `test-??` checks in the PR and a message with the copr instructions. If we don't add the build, there will be only `test-???` checks without any message about copr.

**Comment by psss** [comment]
Unless there is a problem with building the package I would go with `test-*` messages only.

**Comment by lachmanfrantisek** [comment]
> Unless there is a problem with building the package I would go with `test-*` messages only.

Yes, we comment about the (s)rpm build errors in all cases.
