### ISSUE TITLE
Congratulations before rpms are built

### ISSUE THREAD

**Issue by psss** [packit-service/packit-service#288]
It seems the `congratulations` comment is sometimes added before the copr build is completed. Happened just now in https://github.com/psss/tmt/pull/55. Fedora 31 build is still pending in copr but the comment has been already added. Also testing status says:

    packit/testing-farm-fedora-31-x86_64 Pending — Tests are running ... 

But there are no rpms to test with...

**Comment by psss** [comment]
Attaching a screenshot showing the status:

![packit](https://user-images.githubusercontent.com/2803150/70246505-299eaa80-1778-11ea-9ae7-14370cfb7827.png)

**Comment by TomasTomecek** [comment]
related to #279 

(as we discussed in the PR ^, the p-s code we're talking about here will receive a ton of changes (read, bugs) in coming days so the hope is that this would fix itself)

also I recall we discussed within the team, that we would have a mechanism in p-s which would babysit all the worker tasks and if things go bad (this case - the status is not updated after a certain period of time), the babysitter would act upon

**Comment by TomasTomecek** [comment]
So this is now deployed, closing.

Feel free to reopen if you run into it again or find anything suspicious.
