### ISSUE TITLE
Packit SRPM build takes too much time

### ISSUE THREAD

**Issue by psss** [packit-service/packit-service#289]
Several times I've observed that building the SRPM takes quite some time. I tried to do some basic time check on the https://github.com/psss/tmt/pull/55 pull request. Here are the results:

    15:20 ... commit pushed
    15:21 ... travis started, packit SRPM build has just started...
    15:23 ... travis tests completed, packit still building SRPM...
    15:33 ... SRPM was built successfully (finally)

So it takes almost quarter of an hour to build the SRPM which is about 1 second on my laptop. Is there anything blocking the build? I think this delay should definitely be improved.

**Comment by TomasTomecek** [comment]
it seems like it's time to scale # of workers of packit-service up

**Comment by TomasTomecek** [comment]
We have now 3 workers so this should be resolved.

**Comment by psss** [comment]
Tested today on https://github.com/psss/edd/pull/10. Looks better but still the difference is quite significant:

 * local make srpm takes 1 second
 * packit/srpm-build takes 5 minutes

Is there anything else making this simple initial step so slow?

**Comment by TomasTomecek** [comment]
This is why it's slow in the service (and sadly we can't change any of those, short-term):
* all the commands are running in a sandbox - the whole repo is being copied to the sandbox, this is usually a network operation which is brutally slow in the cluster
* it make take a while to get your job scheduled in packit-service
* in the new cluster, we no longer need to copy stuff - we'll be able to use network volumes and share the content like that

Long-term, we are planning on moving packit-service to a cluster with much better performance.

**Comment by psss** [comment]
I see, thanks for clarification. When do you plan to migrate to the new cluster?

**Comment by TomasTomecek** [comment]
as soon as possible, which will likely take weeks/months :/ since the new place is not even close to being ready

**Comment by psss** [comment]
Lately the response time seems to be better. Already moved to the new cluster?

**Comment by lachmanfrantisek** [comment]
> Already moved to the new cluster?

No, unfortunately not yet. Maybe some small tweaks helped that.

**Comment by TomasTomecek** [comment]
Sadly, we're not migrating any time soon :/ we were promised a new place, but it didn't turn out in the end.

Maybe we could revisit this and try to do some optimizations on p-s' side.

**Comment by lachmanfrantisek** [comment]
I don't know why. But it behaves much better now. Some optimization is always nice.
