### ISSUE TITLE
Command used in the re-trigger message

### ISSUE THREAD

**Issue by lachmanfrantisek** [packit-service/packit-service#294]
After #290 , we have `build` alias for copr build. Wee need to update message about build re-trigge and use the right command (`/packit build` or `/packit copr-build`).

Proposed solution:
* `build`: When there is no `copr-build` defined and if it is built because of the tests.
    * (="I don't want to know anything about copr." workflow)
* `copr-build`: When there is a `copr-build` defined in the jobs.
    * (="I am interested in copr." workflow)

**Comment by jpopelka** [comment]
> `build` alias for propose-update

`propose-update` or `copr-build`?

**Comment by lachmanfrantisek** [comment]
> `propose-update` or `copr-build`?

Fixed, thanks!
