### ISSUE TITLE
How to tag our team in the comments

### ISSUE THREAD

**Issue by lachmanfrantisek** [packit-service/packit-service#298]
Is there some way, how to tag our team in the github comments?

See this comment, the `@packit-service/the-packit-team` was not parsed correctly:

![Screenshot from 2019-12-10 08-47-25](https://user-images.githubusercontent.com/20214043/70506179-fd917980-1b29-11ea-825f-8ca0c958a2e7.png)

What about tagging all members of the team? (Looks bad, but should work.)

**Comment by jpopelka** [comment]
test @packit-service/the-packit-team  test

**Comment by lachmanfrantisek** [comment]
> no idea how come it works in my comment but not in the app added one

The comment is from the PR in the external project so maybe we can tag the team only in our organisation.

**Comment by jpopelka** [comment]
[you're right](https://github.com/psss/did/pull/215#issuecomment-564005513)
