### ISSUE TITLE
Deployment policy

### ISSUE THREAD

**Issue by jpopelka** [packit-service/packit-service#3]
At the moment this probably belongs more into [packit-service@gitlab](https://gitlab.cee.redhat.com/user-cont/packit-service), but since I'd like to see it [merged with this repo](https://gitlab.cee.redhat.com/user-cont/packit-service/issues/4) eventually, I fill it here. 

Currently we deploy packit service from [usercont/packit-service:master](https://cloud.docker.com/u/usercont/repository/docker/usercont/packit-service) image, which is continuously built from `master`. (#2 will shuffle this a lot)

We need to think about how to:
- continuously deploy devel version (from `master`) of `packit` into our staging instance
- on demand deploy released `packit` to production instance. It could be devel version as well, but we need to use some tags so that we don't deploy some newer broken commit than the one we've tested in staging

Edit: grooming
* automate deployment to stg - deploy every change
* ~~make sure that both stg and prod packit services can work together (update PR check status names, copr project names, etc.)~~ (done)
* research if we want to use separate branch (`stable`, `prod`) for all the components
  * dockerhub should be able to do builds automatically
  * prod image
* research a way how to trivially revert to a last known working deployment

**Comment by TomasTomecek** [comment]
Yes.

>     * continuously deploy devel version (from `master`) of `packit` into our staging instance

devel version of packit, packit-service and ogr

>     * on demand deploy released `packit` to production instance. It could be devel version as well, but we need to use some tags so that we don't deploy some newer broken commit than the one we've tested in staging

+1

**Comment by TomasTomecek** [comment]
So the only thing which is missing here is the stg CD part, right?

**Comment by rpitonak** [comment]
> So the only thing which is missing here is the stg CD part, right?

Yes, I am going to close this and open a more specific issue.
