### ISSUE TITLE
packit-service-tests-requre : FAILURE

### ISSUE THREAD

**Issue by jpopelka** [packit-service/packit-service#306]
In #303 I forgot to recheck the tests after a new F31-based packit image had been built.

Sorry for that, but now the 'requre' tests are failing with (see [here](https://softwarefactory-project.io/zuul/t/local/build/cfb06a5908734fc081bbb59ef503d166) and [here](https://softwarefactory-project.io/zuul/t/local/build/1dbc5fa3c824478c88bb6f8d50105fe5)) some strange errors.

Maybe we just need to re-generate the requre data, but I'm unable to do that (see https://github.com/packit-service/packit-service/pull/304#issuecomment-566492182) so someone else has to.

**Comment by TomasTomecek** [comment]
they are passing now, closing
