### ISSUE TITLE
whitelist: close the tracking issue when approved or rejected

### ISSUE THREAD

**Issue by TomasTomecek** [packit-service/packit-service#31]

**Comment by rpitonak** [comment]
I didn't implement this intentionally, let me explain my point of view:

When someone (packit service maintainers) approve account on the whitelist, this issue should be closed by the person which did the approval or rejection, to be able to track it down and in some cases maybe explain the reason.

**Comment by TomasTomecek** [comment]
But AFAIK that is not what the internal docs say :D hence this issue.
