### ISSUE TITLE
packit/srpm-build status pending after a failure

### ISSUE THREAD

**Issue by psss** [packit-service/packit-service#312]
When packit/srpm-build fails status says `pending`. See the attached screenshot and the https://github.com/psss/edd/pull/10 pull request.
![pending](https://user-images.githubusercontent.com/2803150/71818875-784aa780-308a-11ea-9ec8-35548bb85668.png)

**Comment by lachmanfrantisek** [comment]
Please, wait for the next Monday to let the code move to production.

**Comment by TomasTomecek** [comment]
I'd say that we could redeploy on Wed given all the recent prod issues.
