### ISSUE TITLE
CoprRequestException: Request is not in JSON format, there is probably a bug in the API code.

### ISSUE THREAD

**Issue by jpopelka** [packit-service/packit-service#316]
* https://sentry.io/organizations/red-hat-0p/issues/1425621957
* https://sentry.io/organizations/red-hat-0p/issues/1343455408

**Comment by TomasTomecek** [comment]
```
httplib	

GET https://copr.fedorainfracloud.org/api_3/project?ownername=packit&projectname=dhodovsk-conman-1 [504]

reason	

Gateway Timeout
```

**Comment by TomasTomecek** [comment]
Ideally, retry the request and hope for the best.

**Comment by jpopelka** [comment]
also: https://github.com/rpm-software-management/dnf/pull/1576#issuecomment-575050466

**Comment by TomasTomecek** [comment]
this is now fixed ^

**Comment by jpopelka** [comment]
> this is now fixed

I think (I might be wrong):
- #688 was about something else
- [NOW it's fixed](https://pagure.io/copr/copr/issue/1228)
