### ISSUE TITLE
No response on validation error of the config

### ISSUE THREAD

**Issue by lachmanfrantisek** [packit-service/packit-service#327]
- sentry: https://sentry.io/organizations/red-hat-0p/issues/1440247249/?project=1767823&query=is%3Aunresolved
- Related PR: https://github.com/packit-service/packit/pull/660

**Comment by dhodovsk** [comment]
Is this duplicate of https://github.com/packit-service/packit-service/issues/70?

**Comment by TomasTomecek** [comment]
...and  https://github.com/packit-service/packit-service/issues/222 :D

**Comment by lachmanfrantisek** [comment]
Duplicate of #222
