### ISSUE TITLE
Proposal for the new status workflow

### ISSUE THREAD

**Issue by lachmanfrantisek** [packit-service/packit-service#330]
# Copr build defined

1. Trigger processed, starting SRPM build
![Screenshot from 2020-01-14 16-47-23](https://user-images.githubusercontent.com/20214043/72359190-217a4900-36ee-11ea-90e4-d40aa277cc5b.png)
2. SRPM created, running RPM build
![Screenshot from 2020-01-14 16-46-20](https://user-images.githubusercontent.com/20214043/72359191-217a4900-36ee-11ea-8ecb-ee33dc2a3671.png)
3.  RPM build passed
![Screenshot from 2020-01-15 15-10-56](https://user-images.githubusercontent.com/20214043/72440519-4e3f6680-37a9-11ea-8f17-76f7b17fc3ab.png)
![Screenshot from 2020-01-14 16-49-52](https://user-images.githubusercontent.com/20214043/72359188-217a4900-36ee-11ea-9e1d-e1a80110534d.png)

## Error during SRPM

![Screenshot from 2020-01-15 14-57-13](https://user-images.githubusercontent.com/20214043/72439513-5d251980-37a7-11ea-919d-4a503fadd9f9.png)
![Screenshot from 2020-01-15 14-55-30](https://user-images.githubusercontent.com/20214043/72439514-5dbdb000-37a7-11ea-9938-612a6638310e.png)

## Error during build

![Screenshot from 2020-01-15 15-09-40](https://user-images.githubusercontent.com/20214043/72440446-20f2b880-37a9-11ea-8651-480543e8e2b0.png)
![Screenshot from 2020-01-15 15-08-50](https://user-images.githubusercontent.com/20214043/72440448-20f2b880-37a9-11ea-8f87-62a9363848b5.png)

**Comment by lachmanfrantisek** [comment]
# Tests defined

1. Trigger processed, starting SRPM build
![Screenshot from 2020-01-15 17-57-08](https://user-images.githubusercontent.com/20214043/72454240-c82f1a00-37c0-11ea-89ff-6bcff3740f45.png)
2. SRPM created, running RPM build
![Screenshot from 2020-01-15 17-58-02](https://user-images.githubusercontent.com/20214043/72454239-c7968380-37c0-11ea-9e6d-9d22b0d6d993.png)
3. RPM build passed, running testing farm
![Screenshot from 2020-01-15 17-59-01](https://user-images.githubusercontent.com/20214043/72454238-c7968380-37c0-11ea-85ea-6f5482bbf4c8.png)
4. Tests passed
![Screenshot from 2020-01-15 18-03-13](https://user-images.githubusercontent.com/20214043/72454533-573c3200-37c1-11ea-9e1e-a3048b44f029.png)

## Error during SRPM

![Screenshot from 2020-01-15 14-57-13](https://user-images.githubusercontent.com/20214043/72454720-ab471680-37c1-11ea-9be7-738cb4adb902.png)
![Screenshot from 2020-01-15 18-21-45](https://user-images.githubusercontent.com/20214043/72455910-f104de80-37c3-11ea-99f0-84fda4098517.png)



## Error during RPM build

![Screenshot from 2020-01-15 15-09-40](https://user-images.githubusercontent.com/20214043/72454677-98ccdd00-37c1-11ea-9cd3-2ca52b30c379.png)
![Screenshot from 2020-01-15 18-18-38](https://user-images.githubusercontent.com/20214043/72455671-8784d000-37c3-11ea-904e-cb195248d6e2.png)

## Error during testing farm
![Screenshot from 2020-01-15 18-09-31](https://user-images.githubusercontent.com/20214043/72455013-44762d00-37c2-11ea-8aab-998a54003517.png)

**Comment by lachmanfrantisek** [comment]
# Tests and copr build defined (the combination of both)

# Tests defined

1. Trigger processed, starting SRPM build
![](https://user-images.githubusercontent.com/20214043/72359190-217a4900-36ee-11ea-90e4-d40aa277cc5b.png)
![Screenshot from 2020-01-15 17-57-08](https://user-images.githubusercontent.com/20214043/72454240-c82f1a00-37c0-11ea-89ff-6bcff3740f45.png)
2. SRPM created, running RPM build
![](https://user-images.githubusercontent.com/20214043/72359191-217a4900-36ee-11ea-8ecb-ee33dc2a3671.png)
![Screenshot from 2020-01-15 17-58-02](https://user-images.githubusercontent.com/20214043/72454239-c7968380-37c0-11ea-9e6d-9d22b0d6d993.png)
3. RPM build passed, running testing farm
![](https://user-images.githubusercontent.com/20214043/72440519-4e3f6680-37a9-11ea-8f17-76f7b17fc3ab.png)
![](https://user-images.githubusercontent.com/20214043/72359188-217a4900-36ee-11ea-9e1d-e1a80110534d.png)
![Screenshot from 2020-01-15 17-59-01](https://user-images.githubusercontent.com/20214043/72454238-c7968380-37c0-11ea-85ea-6f5482bbf4c8.png)
4. Tests passed
![](https://user-images.githubusercontent.com/20214043/72359188-217a4900-36ee-11ea-9e1d-e1a80110534d.png)
![Screenshot from 2020-01-15 18-03-13](https://user-images.githubusercontent.com/20214043/72454533-573c3200-37c1-11ea-9e1e-a3048b44f029.png)

## Error during SRPM

![Screenshot from 2020-01-15 14-57-13](https://user-images.githubusercontent.com/20214043/72454720-ab471680-37c1-11ea-9be7-738cb4adb902.png)
![Screenshot from 2020-01-15 18-21-45](https://user-images.githubusercontent.com/20214043/72455910-f104de80-37c3-11ea-99f0-84fda4098517.png)



## Error during RPM build

![Screenshot from 2020-01-15 15-09-40](https://user-images.githubusercontent.com/20214043/72454677-98ccdd00-37c1-11ea-9cd3-2ca52b30c379.png)
![Screenshot from 2020-01-15 18-18-38](https://user-images.githubusercontent.com/20214043/72455671-8784d000-37c3-11ea-904e-cb195248d6e2.png)

## Error during testing farm
![Screenshot from 2020-01-15 18-09-31](https://user-images.githubusercontent.com/20214043/72455013-44762d00-37c2-11ea-8aab-998a54003517.png)

**Comment by TomasTomecek** [comment]
Looks good and makes sense!

**Comment by dhodovsk** [comment]
LGTM
