### ISSUE TITLE
cannot download source for avocado

### ISSUE THREAD

**Issue by dhodovsk** [packit-service/packit-service#332]
[avocado-framework](https://github.com/avocado-framework/avocado/) fails on SRPM creation
```
PackitSRPMException
Preparing of the upstream to the SRPM build failed: Failed to download file from URL https://github.com/avocado-framework/avocado/archive/74.0.43.g5626d162.tar.gz#/avocado-74.0.43.g5626d162.tar.gz. Reason: 'Not Found'.
```

Example PR - https://github.com/avocado-framework/avocado/pull/3452

**Comment by lachmanfrantisek** [comment]
Duplicate of https://github.com/packit-service/packit-service/issues/313
