### ISSUE TITLE
Testing farm - unable to submit

### ISSUE THREAD

**Issue by dhodovsk** [packit-service/packit-service#341]
We are unable to submit tests in the testing farm:

Request to testing farm: 
```
POST https://scheduler-testing-farm.apps.ci.centos.org/v0/trigger [405]
```
returns `METHOD NOT ALLOWED`

Sentry issue: https://sentry.io/organizations/red-hat-0p/issues/1456553055/

**Comment by thrix** [comment]
Looking

**Comment by thrix** [comment]
Hmm, I see this in logs, could be something in POST changed?

```
[2020-01-20 09:54:25,758] ERROR in scheduler: Required key 'git-ref' in array 'artifact' not found.
ERROR:scheduler:Required key 'git-ref' in array 'artifact' not found.
INFO:werkzeug:10.128.0.1 - - [20/Jan/2020 09:54:25] "POST /v0/trigger HTTP/1.1" 405 -
```

**Comment by TomasTomecek** [comment]
I can see it's being populated: https://github.com/packit-service/packit-service/blob/master/packit_service/worker/testing_farm.py#L142
