### ISSUE TITLE
exception while initiating WS Client: ApiException()

### ISSUE THREAD

**Issue by dhodovsk** [packit-service/packit-service#351]
sentry: https://sentry.io/organizations/red-hat-0p/issues/1369136759/

**Comment by TomasTomecek** [comment]
I thought this would be the same one as "can't initiate WS client: all ports are used" but there is no such message in the logs, so... :/

**Comment by TomasTomecek** [comment]
WHAT?! that doesn't make any sense, there is literally nothing in the logs when there should be a ton of log lines from sandcastle why it failed to init the ws client.

https://github.com/packit-service/sandcastle/blob/master/sandcastle/api.py#L455

**Comment by lachmanfrantisek** [comment]
@TomasTomecek those events are old: https://sentry.io/organizations/red-hat-0p/issues/1369136759/events/?project=1767823&referrer=github_integration (the newest from Feb 12, 2020 11:11:36 AM UTC).

**Comment by jpopelka** [comment]
We haven't seen this for some while. Closing.
