### ISSUE TITLE
Add rpmlint check before building SRPM

### ISSUE THREAD

**Issue by dhodovsk** [packit-service/packit-service#367]
Because that way we and user can have some error information before actual build - e.g. [here](https://github.com/dhodovsk/urlgrabber/pull/1) would make sense: in copr it fails with `  | warning: Macro expanded in comment on line 21: %{version}.tar.gz` this error would be seen before triggered copr build.

We could also add the possibility to disable it in copr job metadata.

**Comment by TomasTomecek** [comment]
it would make sense for us to create new checks for rpmlint, [rpminspect](https://github.com/rpminspect/rpminspect) and print them as separate statuses, or merge them w/ TFT checks

but definitely +1

**Comment by jpopelka** [comment]
I tried to run `rpmlint` on various spec files I have locally (try https://github.com/ycollet/fedora-spec) and see some Errors:
- E: hardcoded-library-path in %{_prefix}/lib/...
- E: specfile-error error: query of specfile systemd.spec failed, can't parse
- E: specfile-error warning: extra tokens at the end of %endif directive in line 55:  %endif # python2 pkg
- E: specfile-error
- E: specfile-error warning: bogus date in %changelog:
- E: specfile-error warning: Macro expanded in comment on line 2: %global debug_package %{nil}

They, from my perspective, have no impact on whether the build will succeed or fail, so we should NOT block the build when seeing them.

So, It might be nice to have `rpmlint` and others as a separate check.
But I don't agree with having it as a pre-step of building SRPM - if it means that the SRPM build would not start in case the `rpmlint` spits some error.

**Comment by TomasTomecek** [comment]
We still wanna do this but we just need to scope it properly.
