### ISSUE TITLE
Two separately configured worker nodes

### ISSUE THREAD

**Issue by jpopelka** [packit-service/packit-service#377]
[Celery documentation says](http://docs.celeryproject.org/en/latest/userguide/optimizing.html#optimizing-prefetch-limit):
"If you have a combination of long- and short-running tasks, the best option is to use two worker nodes that are configured separately, and route the tasks according to the run-time (see [Routing Tasks](http://docs.celeryproject.org/en/latest/userguide/routing.html))."

That's IMHO exactly our case because the tasks which build an SRPM take a loong time while tasks reacting to copr.build.[start|end] take about 10s (see #375).

**Comment by TomasTomecek** [comment]
yes

**Comment by dhodovsk** [comment]
TODO: separate srpm building task from the process_message task in celery.

**Comment by jpopelka** [comment]
Does anyone remember output from our architecture discussion regarding this topic?
A don't see anything on our architecture Etherpad.

**Comment by dhodovsk** [comment]
I think we planned to dedicate one afternoon(or other longer period) for design discussion for this. We had four bullet points with assignees. (1, deep-dive, 2 what we like, 3, what we don't like, ... - something like that).

**Comment by lachmanfrantisek** [comment]
@dhodovsk that was about the service design in general.

We already spend some time discussing the dedicated celery queues, multiple job tasks...

**Comment by TomasTomecek** [comment]
Since we are reworking the tasks I'm in favour of closing this.

**Comment by lachmanfrantisek** [comment]
Yes, this one will be covered by other issues/PRs.
