### ISSUE TITLE
CLI and service generate a different, incompatible tarball

### ISSUE THREAD

**Issue by TomasTomecek** [packit-service/packit-service#379]
https://github.com/justin-stephenson/tlog/pull/6

https://copr-be.cloud.fedoraproject.org/results/packit/justin-stephenson-tlog-6/fedora-29-x86_64/01208070-tlog/builder-live.log.gz

```
Executing(%prep): /bin/sh -e /var/tmp/rpm-tmp.flW5su
+ umask 022
+ cd /builddir/build/BUILD
+ cd /builddir/build/BUILD
+ rm -rf tlog-7
+ /usr/bin/gzip -dc /builddir/build/SOURCES/tlog-7.tar.gz
+ /usr/bin/tar -xof -
+ STATUS=0
+ '[' 0 -ne 0 ']'
+ cd tlog-7
/var/tmp/rpm-tmp.flW5su: line 37: cd: tlog-7: No such file or directory
error: Bad exit status from /var/tmp/rpm-tmp.flW5su (%prep)
```

It works just fine on command line but in service it fails. It seems that the version in generated tarball is different than it's meant to be.

**Comment by jpopelka** [comment]
We have changed the code a lot since then, let's close as hopefully fixed.
