### ISSUE TITLE
"Only collaborators" warning should be removed upon successful execution

### ISSUE THREAD

**Issue by psss** [packit-service/packit-service#382]
For pull requests created by a non-collaborator the following is displayed in the result details:

    packit/rpm-build-fedora-all — Only collaborators can trigger Packit-as-a-Service

This result remains even after manual `/packit build` comment so the overall status will always be `failed`. What about removing the message/result upon a successful manual execution?

**Comment by psss** [comment]
Example pull request: https://github.com/psss/tmt/pull/97

**Comment by lachmanfrantisek** [comment]
Do we want to

- remove that status completely and add that info directly to the status for each build/test chroot?
  - easier code

or

- Add the cleanup for that status.

@dhodovsk WDYT? (We were discussing that multiple times..;)

**Comment by dhodovsk** [comment]
based on what we talked about - check status `packit/rpm-build-fedora-all` should never be set - it should be `packit/rpm-build-fedora-30-x86_64` and similar.
