### ISSUE TITLE
Testing errors are not displayed

### ISSUE THREAD

**Issue by thrix** [packit-service/packit-service#387]
Seems errors do not get to test result description as displayed by Packit. The status stays in `Pending — Tests are running ...`.

Currently this can be seen here:
https://github.com/oamg/convert2rhel/pull/11

Or here:
https://github.com/psss/tmt/pull/26

**Comment by dhodovsk** [comment]
Error message - 'NoneType' object is not iterable
sentry: https://sentry.io/share/issue/617a7789a08e405fab971129247f79da/

**Comment by lachmanfrantisek** [comment]
Maybe I am getting it wrong, but why is the `tests` section not present? Is it an expected scenario?

**Comment by dhodovsk** [comment]
@thrix ^

**Comment by thrix** [comment]
@lachmanfrantisek yes, for errors which completely break execution, we return just error and message, no tests section. Note that this worked before, but was lost seems. Sorry that there is no good for this spec now. We will improve this with api v1 comming in next months.

**Comment by lachmanfrantisek** [comment]
@thrix thanks for the info.

> Note that this worked before, but was lost seems.

Yes, because we totally ignored that field before I fixed that in https://github.com/packit-service/packit-service/pull/365 ...;)

(We need that for https://github.com/packit-service/packit-service/pull/362)

**Comment by thrix** [comment]
Makes sense :) thanks for quick turnaround!

**Comment by dhodovsk** [comment]
Fixed in linked PR
