### ISSUE TITLE
pull request opened from fork - incorrect git repository / ref passed to testing farm

### ISSUE THREAD

**Issue by thrix** [packit-service/packit-service#389]
I am hitting this issue while testing:

https://github.com/oamg/convert2rhel/pull/11

This is a PR opened from a fork. Testing Farm get this request:

```
"artifact": {
  "commit-sha": "b4319b9781f78fda9a2df72f791e033b8d253a77",
  "copr-chroot": "epel-6-x86_64",
  "copr-repo-name": "packit/oamg-convert2rhel-11",
  "git-ref": "b4319b9781f78fda9a2df72f791e033b8d253a77",
   "git-url": "https://github.com/oamg/convert2rhel",
   "repo-name": "convert2rhel",
   "repo-namespace": "oamg"
},
```
But this does not seem to be correct. Note that git-ref/commit-sha is not from this repo, it is really from the fork ...

**Comment by dhodovsk** [comment]
Failed to reproduce - the tests are passing even when the fork is rpitonak's https://github.com/packit-service/hello-world/pull/26

**Comment by thrix** [comment]
This was a issue in testing farm at last, we should not use git on Centos6/7 and hope it will work the same as in later releases. Fixed
