### ISSUE TITLE
packit service should send only a single notif for a succ build

### ISSUE THREAD

**Issue by TomasTomecek** [packit-service/packit-service#4]
The steps will always be the same for a single PR, the service should check if it already commented on the PR and if it did, don't send a new one.

~~If the last comment is from packit service and is about the successful build, don't comment.~~

edit:
our rule: there are no two successful comments from service in a row

**Comment by larskarlitski** [comment]
Hey! We're using (and loving) packit in [osbuild](https://github.com/osbuild/osbuild). We tend to have lots of back-and-forth on pull requests, force pushing regularly. packit's notifications add a lot of clutter, both to the discussion and to notifications.

Honestly, I'd prefer *only* having the status and no comments at all.

**Comment by msehnout** [comment]
> Honestly, I'd prefer _only_ having the status and no comments at all.

This could be a problem, because packit service does not have any other means of displaying output except for the comments. See #105 for more details. I guess this could also be fixed with #41, but that seems to be long term goal...

**Comment by TomasTomecek** [comment]
ok, how about having a field in the config which would disable setting the successful pr comment

**Comment by rpitonak** [comment]
> ok, how about having a field in the config which would disable setting the successful pr comment

+1 to have it configurable.

**Comment by msehnout** [comment]
What about using a single comment and editing it every time packit runs a build?

**Comment by lachmanfrantisek** [comment]
> What about using a single comment and editing it every time packit runs a build?

This does not generate a notification what can be an advantage as well a disadvantage.

**Comment by msehnout** [comment]
> > What about using a single comment and editing it every time packit runs a build?
> 
> This does not generate a notification what can be an advantage as well a disadvantage.

That's not a problem for me, what do you think @larskarlitski ?

**Comment by larskarlitski** [comment]
> That's not a problem for me, what do you think @larskarlitski ?

Not a problem for me either, but I still very much prefer a status only :)

**Comment by msehnout** [comment]
> 
> Not a problem for me either, but I still very much prefer a status only :)

But how do you know where the problem is? You could just blindly try to change something ...

**Comment by TomasTomecek** [comment]
The other idea I had was to delete the last comment from packit-service and add a new one.

**Comment by TomasTomecek** [comment]
I just added this issue into our internal board so hopefully we'd start working on it soon (=weeks).

**Comment by TomasTomecek** [comment]
This is now done and deployed in prod. I'm going to create a new issue for disabling the comments completely.
