### ISSUE TITLE
Storing secrets for test execution

### ISSUE THREAD

**Issue by thrix** [packit-service/packit-service#400]
After discussion with @bkabrda seems that sooner or later we will get into situation that this will be a blocker for somebody onboarding tests via Packit. I am filling this is as a feature request to have conversation how we could have such a functionality. As Testing Farm is not a Github application and has no idea about the project it is testing, seems in current state of things this functionality would need to be in Packit Service.

**Comment by TomasTomecek** [comment]
I hope that we would never need this since getting into secrets' business is so hard and it can easily be done wrong and insecurely.

**Comment by thrix** [comment]
Some related use case from Fedora CI: https://lists.fedorahosted.org/archives/list/ci@lists.fedoraproject.org/thread/ORM3CK73HTZA6S3ARTVVQWKHMVLVRX5E/
