### ISSUE TITLE
tuned build failing with "maximum recursion depth exceeded"

### ISSUE THREAD

**Issue by TomasTomecek** [packit-service/packit-service#415]
https://sentry.io/organizations/red-hat-0p/issues/1450159324/?project=1767823&query=is%3Aunresolved+recursion&statsPeriod=14d

Affecting: https://github.com/redhat-performance/tuned/pull/176

The logs don't make sense to me:
```
SRPM is ./tuned-v2.13.0.24.g73a4c0e-1.fc31.src.rpm
GET https://copr.fedorainfracloud.org/api_3/project?ownername=packit&projectname=redhat-performance-tuned-176 [200]
packit_service.worker.copr_build   There was an error while running a copr build:
maximum recursion depth exceeded while calling a Python object
```

The whole strack trace would be lovely

https://sentry.io/organizations/red-hat-0p/issues/1679285251

**Comment by TomasTomecek** [comment]
Looks like that all the prod builds now fail with this - what happened? how?

**Comment by lachmanfrantisek** [comment]
The link to the related event in sentry since the issue contains all copr-related problems:

https://sentry.io/organizations/red-hat-0p/issues/1450159324/events/95d65fb39e3245dbb60fdee2c7bbc4ee/

**Comment by TomasTomecek** [comment]
So, the error message was coming from copr, right?

We just need to update our code to make it clear that the error message is not ours.

**Comment by TomasTomecek** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1838481

**Comment by TomasTomecek** [comment]
Shall we close this?
