### ISSUE TITLE
handle github pre-release? comment vs. release inconsistency

### ISSUE THREAD

**Issue by dhodovsk** [packit-service/packit-service#423]
For propose update:
 * when the trigger is a GitHub release - packit gains all the info from the webhook and can work with both - releases and pre-releases
 * when the trigger is a comment, packit uses https://developer.github.com/v3/repos/releases/#get-the-latest-release endpoint which does not list GitHub pre-releases.

**Comment by TomasTomecek** [comment]
IMO we should treat releases as prereleases, WDYT?

**Comment by dhodovsk** [comment]
SGTM.

TODO:
 - use https://developer.github.com/v3/repos/releases/#list-releases-for-a-repository endpoint and get the latest release from the list.

**Comment by lbarcziova** [comment]
Resolved in #498
