### ISSUE TITLE
Packit Service API Issues and some suggested additions.

### ISSUE THREAD

**Issue by IceWreck** [packit-service/packit-service#425]
- The packet-service api does not provide the copr build date/time, which is needed for sorting builds by time in relation to packit-service/dashboard#9

-  Also pull request id should be provided alongside other build info in _api/copr-builds/_ (list of all copr builds) instead of having to make new requests to _api/copr-builds/{id}_ (specific build info)

- In some cases _api/copr-builds/{id}_ returns nothing even when _api/copr-builds/_ provides the exact same id. I assume this is unexpected behavior which needs to be fixed. 

Example: In the packet-service **production api**, one of the builds returned by _api/copr-builds/_  (list of all copr builds) is:

` 
 {
    "project": "rpm-software-management-libdnf-768",
    "owner": "packit",
    "chroots": [
      "fedora-rawhide-x86_64",
      "fedora-30-x86_64",
      "fedora-29-x86_64",
      "mageia-cauldron-x86_64",
      "opensuse-tumbleweed-x86_64"
    ],
    "build_id": 997744,
    "status": "failure"
  },
`

However _api/copr-builds/997744_ returns nothing. 

This happens randomly though, for example _api/copr-builds/_ also returns an object with build id 1087767 and in this case _api/copr-builds/1087767_ works perfectly.

**Comment by lachmanfrantisek** [comment]
Thanks for the proposal.

>     * Also pull request id should be provided alongside other build info in _api/copr-builds/_ (list of all copr builds) instead of having to make new requests to _api/copr-builds/{id}_ (specific build info)

- Just to make it clear -- you mean the project-wide id (what we can find in the URL). Not the internal pull-request id for GitHub?
- What about the pull-request URL so we don't need to "guess" it?

> However api/copr-builds/997744 returns nothing.

If I am right, this should be fixed when we migrate to the new database. (This is probably a leftover from the ancient times when we didn't store that value.)

**Comment by IceWreck** [comment]
> This is probably a leftover from the ancient times when we didn't store that value.

Okay, great !

> you mean the project-wide id (what we can find in the URL). Not the internal pull-request id for GitHub?

Yes I was talking about the project wide id. Packit Service already stores that value and sends it in _api/copr-builds/{buildid}_ I just wanted it to send that value in the all builds list too.

> What about the pull-request URL so we don't need to "guess" it?

Thats fine too. It doesn't make a difference because PR links are structured like github.com/owner/repo-name/pull/pull-id 

Although we don't need this addition to the API at all if all the newer builds will provide a build id.

**Comment by lachmanfrantisek** [comment]
> Thats fine too. It doesn't make a difference because PR links are structured like github.com/owner/repo-name/pull/pull-id

We are planning to support also other git-forges (like GitLab), so it will be nice to not need to reinvent the ~~wheel~~/[ogr](https://github.com/packit-service/ogr) everywhere...;)
