### ISSUE TITLE
Pylint plugin for sentry

### ISSUE THREAD

**Issue by lachmanfrantisek** [packit-service/packit-service#428]
What do you think of this: https://github.com/davidszotten/sentry-stack-checker

- Do we want it?
- Do we need it?

**Comment by TomasTomecek** [comment]
Does this mean that the plugin enforces stack traces so they will always be visible in sentry?

**Comment by lachmanfrantisek** [comment]
> Does this mean that the plugin enforces stack traces so they will always be visible in sentry?

I think so, but I haven't read that deeply.
