### ISSUE TITLE
Whitelist does not use correct status

### ISSUE THREAD

**Issue by lachmanfrantisek** [packit-service/packit-service#438]
It looks like we forget to expand the alias somewhere:

![Screenshot from 2020-02-27 12-43-25](https://user-images.githubusercontent.com/20214043/75442022-e27f1a80-595e-11ea-8b7e-002c709efdd5.png)

**Comment by grapheo12** [comment]
Can I look into it?
What is the correct status that should have been used?

**Comment by lachmanfrantisek** [comment]
@grapheo12 It would be fine if you want to look at it!

> What is the correct status that should have been used?

- `fedora-all` is an alias and it should be expanded => there should be the status for each version:
  - `packit/rpm-build-fedora-30`
  - `packit/rpm-build-fedora-31`
  - `packit/rpm-build-fedora-rawhide`

**Comment by grapheo12** [comment]
I have scanned through the codebase. I think Line 68 and 81 in `tests/integration/test_listen_to_fedmsg.py` maybe causing the problem.

Contents of both line:
```python
metadata={"targets": ["fedora-all"]},
```
Should I replace `["fedora-all"]` with `["fedora-30", "fedora-31", "fedora-rawhide"]`

**Comment by lachmanfrantisek** [comment]
> I have scanned through the codebase. I think Line 68 and 81 in `tests/integration/test_listen_to_fedmsg.py` maybe causing the problem.

- The tests should not cause any problems in the production environment. (We need to find the problem in the `packit-service` code (`the `packit-service` directory, probably the worker module).
- In metadata, it's expected to have the raw alias. The problem is when we set the status for whitelist.

**Comment by grapheo12** [comment]
This issue is non-reproducible.
Test PR: https://github.com/packit-service/hello-world/pull/94

**Comment by lachmanfrantisek** [comment]
@grapheo12 thanks for looking at it.
