### ISSUE TITLE
Missing documentation about permissions for triggering builds

### ISSUE THREAD

**Issue by tyll** [packit-service/packit-service#442]
On https://github.com/nmstate/nmstate/pull/576 packit errors with "Only collaborators can trigger Packit-as-a-Service" but the submitter of the PR is a member of the nmstate organization. What are the exact requirements for submitters to trigger a copr build? https://packit.dev/packit-as-a-service/ does not seem to mention this. It would be great if the error message could also be more specific, like "Only submitters with at least .... permissions can trigger copr builds.".

**Comment by csomh** [comment]
Looking at the code

```python
        collaborators = self.project.who_can_merge_pr()
...
```

Following this call as it leads to [ogr](https://github.com/packit-service/ogr/blob/master/ogr/services/github/project.py#L216):

```python
            if permission in ["admin", "write"]:
...
```

So the error message (and the documentation) should say:

```
Only users with write or admin permissions can trigger copr builds.
```

**Comment by csomh** [comment]
Another (somewhat related) idea: would it improve usability if "permission to trigger copr build" would be decoupled from GitHub repository permissions?

**Comment by tyll** [comment]
The requirements seem to be very strict for a copr build. AFAIK, everyone could register an account to build something on Copr. Therefore it does not seem like it is something that should be limited to only trustworthy persons. What am I missing? Travis, for example, also runs for everyone. Therefore I think the projects might not care too much about who is allowed to trigger copr builds.

If it needs to be restricted to trusted persons, it would be nice to whitelist them without having to elevate their GitHub permissions to write or higher.

**Comment by lachmanfrantisek** [comment]
> The requirements seem to be very strict for a copr build. AFAIK, everyone could register an account to build something on Copr. Therefore it does not seem like it is something that should be limited to only trustworthy persons. What am I missing? Travis, for example, also runs for everyone. Therefore I think the projects might not care too much about who is allowed to trigger copr builds.

- Anyone will then be able to run any code during the SRPM build in our infra (in the sandbox, but still).
- Anyone can trigger then be able to run any code during the copr build in the Fedora infra.

This is not the final solution, but now, we want to legally saved and allow installation only for those that sign the FPCA. (And that person is then responsible for the all organisation.)

> If it needs to be restricted to trusted persons, it would be nice to whitelist them without having to elevate their GitHub permissions to write or higher.

Related issue: https://github.com/packit-service/packit-service/issues/250

**Comment by csomh** [comment]
@tyll both the docs and the error messages were updated. Let me know if I missed anything.
