### ISSUE TITLE
Packit-service server-specific config

### ISSUE THREAD

**Issue by TomasTomecek** [packit-service/packit-service#45]
Add a way to control production deployment of packit-service via a config file which is maintained in this repo. Use cases:

* validate webhook secret: yes/no
* command-runner configuration (this is now hacked inside packit's codebase)

The idea here is to not pollute code in packit's codebase with code which is related to the service.

**Comment by rpitonak** [comment]
I have started to work on this. I will send a PR soon and we can discuss the design and all the properties which we want to include.

**Comment by rpitonak** [comment]
Solved in #60
