### ISSUE TITLE
Sentry integrations (update and add new)

### ISSUE THREAD

**Issue by lachmanfrantisek** [packit-service/packit-service#454]
- [ ] We might want to update the sentry SDK.
- [ ] What about the other three recommended integrations, do we want them?

![Screenshot from 2020-03-05 08-21-01](https://user-images.githubusercontent.com/20214043/75957453-56b74200-5eba-11ea-87fa-263c9384e8ff.png)

**Comment by jpopelka** [comment]
I'd definitely try [Flask](https://docs.sentry.io/platforms/python/flask/) & [SQLAlchemy](https://docs.sentry.io/platforms/python/sqlalchemy/). [Redis](https://docs.sentry.io/platforms/python/redis/) doesn't make much sense since we're moving away from it.

**Comment by TomasTomecek** [comment]
I recall I enabled some integration but in the end it didn't do anything.
