### ISSUE TITLE
Propose-downstream fails when project not released to PyPI yet.

### ISSUE THREAD

**Issue by jpopelka** [packit-service/packit-service#469]
See https://github.com/packit-service/ogr/issues/348#issuecomment-596520043 triggered by https://github.com/packit-service/ogr/pull/347#issuecomment-596503222

```
[DEBUG/ForkPoolWorker-1] All jobs finished!
WARNING  {'jobs': {'propose_downstream': {'success': False, 'details': {'msg': 'Propose update failed.', 'errors': {'master': "Failed to download file from URL https://files.pythonhosted.org/packages/source/o/ogr/ogr-0.11.0.tar.gz. Reason: 'Not Found'. ", 'f32': 'The distgit repository /tmp/packit-dist-gitpptwa97d is dirty.This is not supported.', 'f31': 'The distgit repository /tmp/packit-dist-gitpptwa97d is dirty.This is not supported.', 'f30': 'The distgit repository /tmp/packit-dist-gitpptwa97d is dirty.This is not supported.'}}}}, 'event': {'trigger': 'release', 'created_at': 1583757818, 'project_url': 'https://github.com/packit-service/ogr', 'repo_namespace': 'packit-service', 'repo_name': 'ogr', 'tag_name': '0.11.0'}}
ERROR    Propose update failed.
[ERROR/ForkPoolWorker-1] Propose update failed.
```

**Comment by TomasTomecek** [comment]
clearly we need to "wait" for the archive to become available, so retry downloading for 5 times and sleep for 10 seconds between the tries?

**Comment by jpopelka** [comment]
We can definitely try it couple times with some backoff, but most people don't use release-bot, so it might take more than a minute (5x10s) for them to upload it to PyPI (or where else it can be).

If we could perhaps reschedule the task(s) after something like 10 minutes and add a comment into the issue "hey, we failed, but will try in 10 minutes again so if you just haven't uploaded your archive to 'final' destination, do it NOW!" ?

**Comment by TomasTomecek** [comment]
@jpopelka I like it; or maybe even have a config value for them to fill when exactly we should run this - but your solution sounds like a solid default

**Comment by jpopelka** [comment]
still valid
