### ISSUE TITLE
Send the info about version(s) to sentry

### ISSUE THREAD

**Issue by lachmanfrantisek** [packit-service/packit-service#477]
- Followup to https://github.com/packit-service/packit-service/pull/467
- [ ] Set the release for sentry
  - You may load the commit hash from the `/.packit-service.git.commit.hash` file or use the installed version of the package.
  - See the docs: https://docs.sentry.io/workflow/releases/?platform=python#configure-sdk
  - Think about combining the version with the `packit` version.
- [ ] Try to set the setry tags for packit and packit-service versions and/or head commit hashes and/or head commit messages.
  - You can use files (see the https://github.com/packit-service/packit/pull/753 or https://github.com/packit-service/packit-service/pull/467) or installed package versions.
  - docs: https://docs.sentry.io/enriching-error-data/context/?platform=python#tagging-events
  - https://github.com/packit-service/packit-service/blob/6c3c4789cf4631acdd5340f83b91294692f44b46/packit_service/worker/handlers/abstract.py#L82-L85

**Comment by IceWreck** [comment]
I'll try to work on this tomorrow.
