### ISSUE TITLE
Log version(s) at the start

### ISSUE THREAD

**Issue by lachmanfrantisek** [packit-service/packit-service#478]
- [ ] Log version of packit-service and dependant libraries (packit, ogr, ...) at the start of the service/worker.
- [ ] Log that information at the start of each task.
- [ ] Share as much code as possible.

**Comment by TomasTomecek** [comment]
How about doing it also at the start when a task is being processed?

worker logs tend to be super-duper long and this information may get lost

**Comment by devarshigoswami** [comment]
If this isn't resolved, can I try? I would need a little more background info though, quite new to this.

**Comment by lachmanfrantisek** [comment]
@devarshigoswami no, it's not resolved.

The code in this repository is run in two ways -- as a flask web server for the API and a celery worker. We want to log the versions of our libraries on the start.

As @TomasTomecek suggested, it would be nice to log this also for each task the worker is processing. (See the `packit_service/worker/jobs.py`...)

**Comment by IceWreck** [comment]
@devarshigoswami Are you working on this? If not, I'll take it up.

**Comment by devarshigoswami** [comment]
@IceWreck Feel free to do so :) I am preoccupied with something else rn.
