### ISSUE TITLE
picking up packit.yml from target branch vs. from the PR

### ISSUE THREAD

**Issue by TomasTomecek** [packit-service/packit-service#48]
* [x] document current behaviour https://github.com/packit-service/packit.dev/pull/31
* [ ] let upstream maintainers define how p-s should pick up the config file (PR vs. target branch)

CC @dmach

**Comment by lachmanfrantisek** [comment]
>  let upstream maintainers define how p-s should pick up the config file (PR vs. target branch)

Do we want this?

**Comment by TomasTomecek** [comment]
> > let upstream maintainers define how p-s should pick up the config file (PR vs. target branch)
> 
> Do we want this?

That's the question and worth a discussion.

**Comment by lachmanfrantisek** [comment]
Personally, I am used to the config from PR, as it is in zuul/gitlab-ci/... I am able to play with the CI easily.

(I have only one problem with that with signature checking that has to be used from master. But there, we are using the downstream config.)

**Comment by TomasTomecek** [comment]
In terms of security, packit-service will not run if a contributor opens a pull request - the upstream maintainer needs to explicitly trigger packit-service - after the change gets reviewed.

Therefore we don't feel like this is something important to implement on our side and hence we're closing this issue.
