### ISSUE TITLE
Packit is not updating the GitHub PR status

### ISSUE THREAD

**Issue by puiterwijk** [packit-service/packit-service#482]
I have submitted https://github.com/fedora-iot/zezere/pull/41, but even though the COPR build is marked as succesful, the Packit status is Pending.

**Comment by jpopelka** [comment]
We know about this, it's fedora-infra (fedora-messaging) issue and it's being investigated. Sorry

**Comment by jpopelka** [comment]
It should be resolved now. You can re-trigger it with `/packit build`

**Comment by jpopelka** [comment]
Closing, we have #334 to improve UX in such cases.
