### ISSUE TITLE
introduce tests for the API

### ISSUE THREAD

**Issue by TomasTomecek** [packit-service/packit-service#489]
I did not have the heart to ask @IceWreck to write API tests for his PR https://github.com/packit-service/packit-service/pull/479

But we should start testing the API code as well. I'd start with the calls which are migrated to psql.

**Comment by lachmanfrantisek** [comment]
The Schemathesis can be helpful for some validation and for testing the deployment (see  #368 ). I am not sure if we can use it for writting custom tests.

**Comment by TomasTomecek** [comment]
my expectation here is functional tests: store some objects in DB and make sure you're getting the expected data in the API responses
