### ISSUE TITLE
 Flask-RESTPlus is unmaintained, development has moved to Flask-RestX.

### ISSUE THREAD

**Issue by IceWreck** [packit-service/packit-service#494]
We are using FlaskPlus for the API, but the project is [dead](https://github.com/noirbizarre/flask-restplus). 

It had to be forked by the old maintainers ( [drama here](https://github.com/noirbizarre/flask-restplus/issues/770 ) ), the new repo is at https://github.com/python-restx/flask-restx

Since the code is backwards compatible, we have to do an import name change and change the dependency from the dnf package of restplus to restx's pip package. (not in dnf yet)

**Comment by TomasTomecek** [comment]
uhhhh...

@IceWreck thanks for raising this

[django? :smiling_imp:]

**Comment by jpopelka** [comment]
oh, thanks, will take care of the fedora RPMs

**Comment by jpopelka** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1817535
needs a Fedora Reviewer
(https://fedoraproject.org/wiki/Package_Renaming_Process#Re-review_required)
