### ISSUE TITLE
Copr URLs are wrong for groups

### ISSUE THREAD

**Issue by lachmanfrantisek** [packit-service/packit-service#523]
The copr URLs for groups (starting with `@`) are different.

> @sturivny, @lachmanfrantisek, @TomasTomecek, building in the custom copr works. That's great!
> 
> The log linked by packit for the RPM build however points to an invalid copr build URL.
>
> The log: https://prod.packit.dev/copr-build/3500/logs
> The invalid link in the log: https://copr.fedorainfracloud.org/coprs/@oamg/convert2rhel/build/1321726/
> The link that works: https://copr.fedorainfracloud.org/coprs/g/oamg/convert2rhel/build/1321726/

_Originally posted by @bocekm in https://github.com/oamg/convert2rhel/pull/27#issuecomment-604972368_

> @sturivny, @lachmanfrantisek, @TomasTomecek
Also, the testing farm is trying to install the convert2rhel build from an invalid copr repo URL.
> Testing farm log: https://console-testing-farm.apps.ci.centos.org/pipeline/1bb7bded-36e2-4b9b-b34f-47333aaf418e
> It tries to install the pkg from: https://copr.fedorainfracloud.org/coprs/@oamg/oamg-convert2rhel-27/repo/epel-6/oamg-convert2rhel-27-epel-6.repo
It should be installing it from: https://copr.fedorainfracloud.org/coprs/g/oamg/convert2rhel/repo/epel-6/group_oamg-convert2rhel-epel-6.repo

_Originally posted by @bocekm in https://github.com/oamg/convert2rhel/pull/27#issuecomment-604974158_

**Comment by csomh** [comment]
The PRs above should have fixed this issue (and I should have closed it long ago), but still copr build URLs are invalid in the logs, though the repo URLs seem to be fine ([logs](https://console-testing-farm.apps.ci.centos.org/pipeline/859d1ad0-5615-4af1-a34e-07c7555d39ad))

```
[18:05:15] [+] [cruncher] [/plans/smoke] [prepare] Installing builds from copr
# cd /etc/yum.repos.d && curl -LO https://copr.fedorainfracloud.org/coprs/@oamg/convert2rhel/repo/epel-6/convert2rhel-epel-6.repo
% Total % Received % Xferd Average Speed Time Time Time Current
Dload Upload Total Spent Left Speed
127 382 127 382 0 0 952 0 --:--:-- --:--:-- --:--:-- 9794
# repoquery --disablerepo=* --enablerepo=copr:copr.fedorainfracloud.org:@oamg:convert2rhel '*' | grep -v \.src | xargs dnf -y install
Loaded plugins: fastestmirror, presto
Error: Need to pass a list of pkgs to install
```

I'll try to check on this.

**Comment by csomh** [comment]
The copr build URLs are wrong b/c packit-service/packit#780 above was not correctly released.

Installation fails, b/c Testing Farm doesn't use the correct repo name: instead of `copr:copr.fedorainfracloud.org:@oamg:convert2rhel` it should be `copr:copr.fedorainfracloud.org:group_oamg:convert2rhel`. I'm discussing with @thrix how to fix this.

**Comment by csomh** [comment]
Re-built Packit Service images and updated the deployment. Links to copr builds are okay now, see https://prod.packit.dev/copr-build/5155/logs

**Comment by bocekm** [comment]
The Testing Farm is still unable to install the convert2rhel package. The Farm calls the following `repoquery` cmd which is wrong - it returns nothing:

`repoquery --disablerepo=* --enablerepo=copr:copr.fedorainfracloud.org:@oamg:convert2rhel '*' | grep -v \.src | xargs dnf -y install`

There shouldn't be just asterisk, but rather the build version that has just been built for the PR. E.g.:

`repoquery --disablerepo=* --enablerepo=copr:copr.fedorainfracloud.org:@oamg:convert2rhel '*v0.9-1.20200409153013426150*' | grep -v \.src | xargs dnf -y install`

I'm not sure if it still falls under this issue or new issue should be filed for the testing farm.

**Comment by thrix** [comment]
> The copr build URLs are wrong b/c [packit-service/packit#780](https://github.com/packit-service/packit/pull/780) above was not correctly released.
> 
> Installation fails, b/c Testing Farm doesn't use the correct repo name: instead of `copr:copr.fedorainfracloud.org:@oamg:convert2rhel` it should be `copr:copr.fedorainfracloud.org:group_oamg:convert2rhel`. I'm discussing with @thrix how to fix this.

Actually @csomh created a patch and I am deploying it now. Not sure about the other issue though ....

**Comment by thrix** [comment]
FTR https://gitlab.com/testing-farm/cruncher/-/merge_requests/13

**Comment by csomh** [comment]
It seems that there were successful builds and test runs for oamg/convert2rhel#27, so closing this.

Thanks @thrix for your help and thank you @bocekm for your patience!

**Comment by bocekm** [comment]
Awesome, thanks, guys.

**Comment by TomasTomecek** [comment]
@lachmanfrantisek @csomh thank you for taking care of this and finishing it for real! you're heroes
