### ISSUE TITLE
disable interacting with private GitHub repos

### ISSUE THREAD

**Issue by TomasTomecek** [packit-service/packit-service#53]
Since all the services we interact with are open, we shouldn't be able to work with private GitHub repositories - the code might not be open source.

Also add new check to whitelist whether the repo is private or not.

**Comment by jpopelka** [comment]
> Also add new check to whitelist whether the repo is private or not.

I don't understand how the check (whether a repo is private) relates to whitelist (of user accounts).

**Comment by rpitonak** [comment]
Whitelist check is performed before every packit action. Since the same applies to the private repo check it just seems like a reasonable option to implement it there.

On the other hand, I agree with you that they are not fully related to each other.
