### ISSUE TITLE
Unknown field fas_passwd duing PS API call

### ISSUE THREAD

**Issue by rishavanand** [packit-service/packit-service#563]
- This error is related to #552 
- It is thrown during `/api/copr-builds/<id>` API call
```
marshmallow.exceptions.ValidationError: {'fas_passwd': ['Unknown field.']}
```

Is this field needed in the `packit-service`[packit-service.yaml](https://github.com/packit-service/deployment/blob/master/secrets/template/packit-service.yaml)?

**Comment by IceWreck** [comment]
Yeah, I was getting it too. I just removed this field from packit-service.yaml and it works fine for my local deployment as it is optional and has a default value and I was not using any feature that required fas anyway.

**Comment by jpopelka** [comment]
Please check whether https://github.com/packit-service/deployment/pull/76 fixes it and close this if so. Thanks!

**Comment by IceWreck** [comment]
Yes, just checked, its fixed.

**Comment by rishavanand** [comment]
Yes, it's been been fixed 😄 
Thanks!
