### ISSUE TITLE
COPR build start and end time not recorded

### ISSUE THREAD

**Issue by rishavanand** [packit-service/packit-service#566]
After the successful COPR build start and end time is not recorded in the database.  Thus `/api/copr-build/id` returns:
```
{
    ....
    "build_submitted_time": "15/04/2020 18:10:32",
    "build_start_time": null,
    "build_finished_time": null,
    ....
}
```
I traced `CoprBuildEndHandler` and found only the final state is being recorded. 

If it is not being worked on, I can take it up.

**Comment by lbarcziova** [comment]
Thanks for reporting! It is not being worked on, so feel free to take it up
