### ISSUE TITLE
propose_downstream fails with an invalid/expired API token

### ISSUE THREAD

**Issue by ernestask** [packit-service/packit-service#587]
Context: https://github.com/abrt/reportd/issues/10

I’m not quite sure if there’s anything missing on our side.

**Comment by ernestask** [comment]
And a nitpick: seems that both packit-service and ogr are using backquotes in error messages, so the end result is a bit messy.

**Comment by jpopelka** [comment]
> I’m not quite sure if there’s anything missing on our side.

No, it's ours and I'm sorry about that.
I updated the configuration with a new token a few hours before the abrt/reportd#10 happened, but probably the workers didn't reload it or maybe I hadn't given the token enough permission.
Anyway, I've created a new token now, updated configuration and restarted the workers, so it should work OK.

**Comment by ernestask** [comment]
Worked out fine, thanks a bunch.

**Comment by jpopelka** [comment]
> seems that both packit-service and ogr are using backquotes in error messages, so the end result is a bit messy

https://github.com/packit-service/ogr/issues/396
