### ISSUE TITLE
Apache memory consumption

### ISSUE THREAD

**Issue by jpopelka** [packit-service/packit-service#594]
`packit-service` pod consumes 200Mib even before it starts to do anything.

Could [the config](https://github.com/packit-service/deployment/blob/master/openshift/cmap-packit-httpd-conf.yml.j2) be tweaked [somehow to lower it](https://www.google.cz/search?q=lower+apache+memory+usage)?

**Comment by TomasTomecek** [comment]
how about we switched to nginx :imp:

**Comment by csomh** [comment]
> how about we switched to nginx

Is a 200 Mib consumption at the moment? When do we reach the load when it will be? What is going to be improved if we spend the time to switch to nginx? Is spending this time a worthwhile trade-off?

**Comment by TomasTomecek** [comment]
Are you asking too many questions?

> What is going to be improved if we spend the time to switch to nginx?

I get the feeling that nginx is perceived as more efficient web server: faster and consumes less memory. Agreed though that a switch would be a lot of work for a little benefit (at this point).
