### ISSUE TITLE
Members of a GH organization with write access can't use packit

### ISSUE THREAD

**Issue by bocekm** [packit-service/packit-service#612]
@fellipeh has created this PR https://github.com/oamg/convert2rhel/pull/39 but packit says `Only users with write or admin permissions to the repository can trigger Packit-as-a-Service` even though he has the write access to the repository.

You can see on the following screenshot that 21 members (of the [oamg organization](https://github.com/oamg)) have the write access:
![Screenshot from 2020-05-07 16-04-08](https://user-images.githubusercontent.com/9884110/81304455-9a6e2980-906c-11ea-9808-ed1f37edb476.png)

When I click on the Manage button on the page above, I see that the members of oamg org have really the write permissions:
![Screenshot from 2020-05-07 16-04-36](https://user-images.githubusercontent.com/9884110/81304447-980bcf80-906c-11ea-901b-997df4f92072.png)

Here's a screenshot showing that @fellipeh is a member of the oamg org:
![Screenshot from 2020-05-07 16-05-08](https://user-images.githubusercontent.com/9884110/81304434-9510df00-906c-11ea-9b91-e8b011316517.png)

**Comment by bocekm** [comment]
@fellipeh, please try commenting `\packit test` under the https://github.com/oamg/convert2rhel/pull/39 again.

**Comment by fellipeh** [comment]
@bocekm  same error:

![image](https://user-images.githubusercontent.com/2904206/81682430-36ac7d80-942b-11ea-8da8-279e596b92c8.png)

**Comment by TomasTomecek** [comment]
@bocekm @fellipeh even though this seems to be fixed in our codebase, I'm pretty sure the change is not deployed to production. It will be up on Monday May 18th, unless @csomh decides to deploy it sooner.

**Comment by csomh** [comment]
Yeah, that's right, new deployments usually happen on Monday morning, but we might have one sooner today. Anyways, I did not forget about this issue and I'll keep you posted.

(We will think about how to make this more transparent for you guys.)

**Comment by bocekm** [comment]
Ah, ok, thanks for letting us know. No hurry.

**Comment by jpopelka** [comment]
Production has just been redeployed and should include the fix/change now.

**Comment by fellipeh** [comment]
> Production has just been redeployed and should include the fix/change now.

@jpopelka  Still failing.. 

![image](https://user-images.githubusercontent.com/2904206/81823377-a6456a00-950a-11ea-96c1-864f6d339cc3.png)

**Comment by jpopelka** [comment]
> Still failing..

Right, I was just told (@csomh) that we hadn't pulled in the [ogr change](https://github.com/packit-service/ogr/pull/410) so the production is not yet fixed, indeed, sorry for the noise.

> Ah, ok, thanks for letting us know. No hurry.

Given it's Thursday already, let's wait for the regular weekend's re-deployment.

**Comment by csomh** [comment]
@fellipeh please give it another try :crossed_fingers:

**Comment by fellipeh** [comment]
@csomh  Now it's failing only on 2 actions

One question: the packit action depends of pylint actions?

![image](https://user-images.githubusercontent.com/2904206/81938991-1ec02f80-95cc-11ea-8d75-9066d362e245.png)

**Comment by csomh** [comment]
@fellipeh That's weird and probably is related to #535.

I think the failures are left-overs from previous runs. Could you try `/packit build` and see if they are fixed? Pushing to the branch would have a similar effect (that would re-trigger both builds and tests).

**Comment by fellipeh** [comment]
@csomh Works fine now.. I could run without issue:

![image](https://user-images.githubusercontent.com/2904206/81967459-5392ad80-95f1-11ea-9e1d-7041d341d875.png)

**Comment by bocekm** [comment]
@csomh, thanks!
