### ISSUE TITLE
[DB] celery_taskmeta vs. task_results

### ISSUE THREAD

**Issue by jpopelka** [packit-service/packit-service#617]
On today's arch meeting we realized that the 2 DB tables which take the most space are almost the same size and @lbarcziova  confirmed that they contain almost the same data.

I think:
- `celery_taskmeta` is the celery backend - automatically stored task results
  - [can be easily turned off](https://docs.celeryproject.org/en/stable/userguide/tasks.html#ignore-results-you-don-t-want)
- `task_results` is what we [store exlicitly](https://github.com/packit-service/packit-service/blob/master/packit_service/models.py#L715)

Do we really need both, or we can drop one?

EDIT: Looks similar to #173 (back in the Redis days)

**Comment by csomh** [comment]
Thank you for filing this! :medal_sports: 

> * `task_results` is what we [store exlicitly](https://github.com/packit-service/packit-service/blob/master/packit_service/models.py#L715)

Is the assumption correct that explicitly storing the task results was implemented to be able to serve the `/tasks` API endpoint.

Wondering what was the motivation to introduce that endpoint? Who is the intended user of that endpoint? (Nor #167 nor the related issue, #41, has an explanation for it.)

**Comment by jpopelka** [comment]
> Is the assumption correct that explicitly storing the task results was implemented to be able to serve the `/tasks` API endpoint. Wondering what was the motivation to introduce that endpoint? Who is the intended user of that endpoint?

Ok, let me tell you a story.
Once upon a time in a very distant cluster, there was living this ps service.
Its herdsmen boss wanted to see some rough numbers about how it's doing so the herdsmen started collecting all the possible data (redis hashes) hoping that they might be useful someday when they have enough of them.
When the day came they realized that the boss doesn't understand their scribbles and they need to translate them into something presentable.
(ok, enough, let's switch to english)
So I was creating an API endpoint for each hash.
We had not discussed what data to provide via API, it was just evolution - that we'll later discuss/decide what data are actually useful/useless to store & provide to users.
During that task, I realized that we have two hashes with celery tasks results:

1. `celery-task-meta` hash (equivalent of the current `celery-taskmeta` table) - the `/tasks` endpoint was implemented (in #167) to present data from this hash
2. `celery-tasks` hash - I realized that this one explicitly stores data we already have auto-stored by celery in `celery-task-meta`, thus is redundant and we can drop it (in #173)

When we started transforming redis hashes to postgres tables I was saying in some comments that that's the moment when we should stop and think about what we actually want in those tables and what not anymore and the same for the API endpoints. But I was not loud enough and had other priorities so ... when and why the 'explicitly storing the task results' emerged again is a question I have no answer for.

**Comment by lbarcziova** [comment]
In #520 there are related comments and also explanation what these 2 tables store. The `/tasks` endpoint takes the data from the table created by us (`task_results`)
> Looks like a topic for arch meeting - what/why to actually store (ps tables), provide (API endpoints) and present to users (dashboard).

+1

**Comment by TomasTomecek** [comment]
> Is the assumption correct that explicitly storing the task results was implemented to be able to serve the `/tasks` API endpoint.
> 
> Wondering what was the motivation to introduce that endpoint? Who is the intended user of that endpoint? (Nor #167 nor the related issue, #41, has an explanation for it.)

definitely dashboard and metrics - so that we know what's happening

**Comment by csomh** [comment]
> definitely dashboard and metrics - so that we know what's happening

We deploy [flower](https://github.com/packit-service/deployment/blob/master/openshift/flower.yml), which can be used to monitor the queue. For the dashboard: what is the value in presenting the tasks there, too?

I feel, that the `tasks` endpoint and `TaskResultModel` could be dropped and a periodic job could be set up to clear old data from `celery_taskmeta` (keep maybe the last 30 days or so).

**Comment by csomh** [comment]
We agreed today, that we are going to drop `TaskResultModel` and the `/tasks` endpoint and set up some mechanism to keep only 30 days worth of data in `celery_taskmeta`.

**Comment by lbarcziova** [comment]
Resolved by #735 #742
