### ISSUE TITLE
Packit should cleanup copr repo for each pull request update

### ISSUE THREAD

**Issue by psss** [packit-service/packit-service#628]
If a package structure change happens (such as package rename with obsoletes) during an open pull request, testing farm (cruncher) is unable to install packages from copr because `dnf repoquery --latest 1` returns both old and new packages (because of the different name). Here's a real-life [example](https://console-testing-farm.apps.ci.centos.org/pipeline/800aec6c-ff09-487f-832b-264769e977bb).

Would it make sense to remove old build from copr before building new ones? The issue might not happen that often but it affects all open pull requests of a project when the code is rebased on the spec file changes.

Or could/should we fix this in cruncher? @thrix, what do you think?

**Comment by psss** [comment]
Pasting example output:

```
# dnf -q repoquery --latest 1 --disablerepo=* --enablerepo=copr:$(dnf -y copr list enabled | grep "packit/psss-tmt-250" | tr "/" ":") | grep -v \.src | xargs dnf -y install --allowerasing
Extra Packages for Enterprise Linux Modular 8 - 313 kB/s | 118 kB 00:00‣
Extra Packages for Enterprise Linux 8 - x86_64 32 MB/s | 6.7 MB 00:00
Error: Problem 1: package tmt-provision-container-0.16-1.20200523064805539476.el8.noarch obsoletes tmt-container < 0.17 provided by tmt-container-0.16-1.20200522114010327850.el8.noarch
- conflicting requests
Problem 2: package tmt-provision-virtual-0.16-1.20200523064805539476.el8.noarch obsoletes tmt-testcloud < 0.17 provided by tmt-testcloud-0.16-1.20200522114010327850.el8.noarch
- conflicting requests
(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)
```

**Comment by lachmanfrantisek** [comment]
@psss that is a valid use-case. People might want to play with the dependencies in one PR and see if it builds/installs well.

@/packit-service/the-packit-team
- Can this break logs (and other info) for older builds? Do we want to preserve that?
- How can we do that? (I hope we can use copr package for that.)

**Comment by csomh** [comment]
Tests run on builds done by Packit, right? Would providing the list of packages built to Testing Farm, so that they can be explicitly installed, work? I see this as a much cleaner solution than cleaning up the Copr repo.

**Comment by lachmanfrantisek** [comment]
> Tests run on builds done by Packit, right? Would providing the list of packages built to Testing Farm, so that they can be explicitly installed, work? I see this as a much cleaner solution than cleaning up the Copr repo.

Tests run on builds done by copr triggered from SRPM created by packit.

This will leave the same task to us. We will need to determine, what RPMs are relevant for the latest build.
- using `repoquery`
- parsing the spec-file

Side node -- package specification will be possible in the new testing-farm API. (I am only not sure if we can enable our copr-repo before that.)

**Comment by TomasTomecek** [comment]
> Tests run on builds done by Packit, right? Would providing the list of packages built to Testing Farm, so that they can be explicitly installed, work? I see this as a much cleaner solution than cleaning up the Copr repo.

Completely agree here. I don't think it's reasonable (or even doable - does copr support such a thing?) to mess with the content of the repository when we should be able to pick a list of NVRs which were produced from a single srpm build and passed those to TFT

**Comment by csomh** [comment]
> > Tests run on builds done by Packit, right? Would providing the list of packages built to Testing Farm, so that they can be explicitly installed, work? I see this as a much cleaner solution than cleaning up the Copr repo.
> 
> Tests run on builds done by copr triggered from SRPM created by packit.
> 
> This will leave the same task to us. We will need to determine, what RPMs are relevant for the latest build.
> 
> * using `repoquery`
> * parsing the spec-file

Or asking Copr.

Copr already has a list of "Built packages" in the web UI, the only catch is that only their v2 API provides this information atm (or at least copr web UI is using the v2 API).

**Comment by psss** [comment]
Yes, agreed. Providing the correct list of built packages to TFT seems to be the best solution.

**Comment by lachmanfrantisek** [comment]
> Yes, agreed. Providing the correct list of built packages to TFT seems to be the best solution.

Is it worth changing this in cruncher? (Or support that in the new API. => I've made [a comment](https://gitlab.com/testing-farm/api/-/merge_requests/1#note_348741656) about that in the review of the new API.)

**Comment by psss** [comment]
I would say it's enough for the new api. @thrix, what do you think?

**Comment by thrix** [comment]
I added that to the new API:

https://gitlab.com/testing-farm/api/-/blob/master/testing-farm.yaml#L326

Also seems this would solve the problem @bockem has with:

https://gitlab.com/testing-farm/cruncher/-/issues/5

@lachmanfrantisek please start also exposing it in the current API if you can, seems to properly solve ^ I will need it anyway to be done soon

**Comment by lachmanfrantisek** [comment]
I've just created a new issue for that:
https://github.com/packit-service/packit-service/issues/642

Can we close this one?

**Comment by psss** [comment]
Yes, let's track it there.
