### ISSUE TITLE
WebUI for accessing postgres in dev environment

### ISSUE THREAD

**Issue by IceWreck** [packit-service/packit-service#630]
May I add something like [adminer](https://www.adminer.org/en/) to the docker-compose (which, as far as I know is only used for development)  ?

Its easier to find something this way compared to entering the postgres container's shell and then using the psql cli

**Comment by TomasTomecek** [comment]
+1 d-c

I personally still prefer cli over some web ui non-sense, but that's just me, thanks for taking time to propose this
