### ISSUE TITLE
`/api/projects` end-point

### ISSUE THREAD

**Issue by csomh** [packit-service/packit-service#638]
This should also include end-point to get a project by id (or name?)

This issues needs to better defined by @IceWreck and @csomh when the time comes.

**Comment by csomh** [comment]
Ideas:

#### GET /projects

```json
[
    {
        "namespace": "packit-service",
        "name": "hello-world"
    },
    .
    .
    .
]
```

#### GET /projects/packit-service/hello-world
#### GET /projects/\<project-id\>
```json
{
    "namespace": "packit-service",
    "name": "hello-world",
    "stats": {
        "copr_builds": {
            "pull_requests": 10,
            "commits": 2,
            "releases": 1
        },
        "tests": 24,
        "koji_builds": 0,
    }
}
```

**Comment by TomasTomecek** [comment]
shouldn't it be `/api/projects`?

**Comment by csomh** [comment]
> shouldn't it be `/api/projects`?

Indeed. Thanks for pointing out!

**Comment by lachmanfrantisek** [comment]
We should also consider adding an instance or project URL since `namespace` and `name` is not unique.

e.g. we have both packit-service/hello-world on [GitHub](https://github.com/packit-service/hello-world) as well as on [gitlab.com](https://gitlab.com/packit-service/hello-world).

**Comment by lachmanfrantisek** [comment]
> "name": "hello-world"

We are using `repo_name` (`LocalProject`), `project_name` (`models.py`) or `repo` (ogr) across the code. We should try not to introduce new one..;) (And ideally, reduce their number.)

**Comment by csomh** [comment]
Thanks @lachmanfrantisek I've updated the example with your recommendations.

**Comment by lachmanfrantisek** [comment]
> Thanks @lachmanfrantisek I've updated the example with your recommendations.

Thanks, what about having that info also in the `/api/projects`?
