### ISSUE TITLE
Packit as a Service failed on pull requests

### ISSUE THREAD

**Issue by StykMartin** [packit-service/packit-service#644]
When I submit a new pull request I received following failure on all builds: `Submit of the build failed: Object of type set is not JSON serializable`.

Is this something new?

**Comment by ernestask** [comment]
Same thing happening to me: https://github.com/abrt/retrace-server/pull/323.

**Comment by lachmanfrantisek** [comment]
Thank's for the info. The problem was fix by #643, was tested on stage and is being built for production. (Should be there in an hour or two.)

Sorry for the inconvenience.

I'll update you here once ready.

**Comment by lachmanfrantisek** [comment]
The built was quicker than expected. Everything should be fine now. Please, retrigger the build with `/packit build`.
