### ISSUE TITLE
branch pushes events: these are my expectations

### ISSUE THREAD

**Issue by TomasTomecek** [packit-service/packit-service#692]
I just had a conversation w/ @lachmanfrantisek about builds of pushes to a branch, these are my expectations how it's suppose to work:

* a push to any branch in the upstream repo triggers p-s
  * if packit.yaml on that branch has this: `{jobs: [{job: build, trigger: commit}]}`, the build is triggered

~~Franta says that these need to be defined on master branch for all other branches - that's not intuitive to me, also some repos may not even have a master branch (hello ansible).~~

This is suggestion to improve UX so people don't need to set `metadata -> branch: ...` in the branch's packit.yaml

**Comment by lachmanfrantisek** [comment]
> Franta says that these need to be defined on master branch for all other branches - that's not intuitive to me, also some repos may not even have a master branch (hello ansible).

No, that was not what I meant..;-)

If we build in each branch with a valid config with present job config. It will run for the build for push to any branch that starts from `master` after we add that config: e.g. `stable`, upstream->upstream PR branches. Mostly all branches present in the upstream repository.

**Comment by lachmanfrantisek** [comment]
By now, it works like this:

- we push a new commit to the branch `a`
- we load the config from that commit
- if `a` is configured in the job config, we trigger the build

(If `a=master`, you don't need to define branch in config.)

**Comment by TomasTomecek** [comment]
so it works as I expected then, right? :D

**Comment by lachmanfrantisek** [comment]
> so it works as I expected then, right? :D

I hope so..;) You only need to specify that branch in the config.

Example:
- https://github.com/packit-service/hello-world/commits/the-build-branch
- `master` does not contain config with branch build
- `the-build-branch` does contain the config:
    ```yaml
    - job: copr_build
      trigger: commit
      metadata:
        branch: the-build-branch
    ```

**Comment by TomasTomecek** [comment]
nice, works! https://github.com/packit-service/docker-py-source-git/commit/d4d8dbd739c6c0db073e1579570168b8eeec08c1

**Comment by lachmanfrantisek** [comment]
> but still, I feel like the `metadata -> branch: ...` is redundant

Let's use `packit` as an example in the situation where we don't force to specify a branch (your proposal):
- We will add this job to config and merge to master. (`1. master build`)
- We will create a new PR and merge it. (`2. master build`, still works well)
- We will move the `stable` branch to the HEAD commit of master (`stable build`)
- Release-bot will create a new branch for release PR (`0.10.2 build` for each commit in that PR, in case of PR builds, we will build two times for each commit.)

Do we want to have all these builds done automatically? I think it's better to specify only the relevant branches to avoid lot of builds that are not needed.

**Comment by csomh** [comment]
How can one disable builds for the master branch?

Wouldn't be better to have builds for branches disabled by default for all branches, except when explicitly enabled with `metadata.branch`?

**Comment by lachmanfrantisek** [comment]
> Wouldn't be better to have builds for branches disabled by default for all branches, except when explicitly enabled with `metadata.branch`?

That's how it works for now: you need to specify branch to enable builds. The exception with `master` is that you don't need to add `metadata.branch` but you still need to define job. (=> You are manually turning master-builds on by adding job-config without `metadata.branch`.)

> How can one disable builds for the master branch?

- By doing nothing. (No config with `commit` trigger.)
- Using `metadata.branch` if you want to build in another branch.

**Comment by lachmanfrantisek** [comment]
Looks like we (=I) need to document this behaviour at least.

**Comment by csomh** [comment]
> > How can one disable builds for the master branch?
> 
> * By doing nothing. (No config with `commit` trigger.)
> * Using `metadata.branch` if you want to build in another branch.

I see, thanks for the explanation! So for the commit trigger, the master branch is the default currently.

I was actually thinking whether it would make sense to have "on any branch" be the default instead. This is the way it's done in GitLab pipelines, and then they use [`only/except`](https://docs.gitlab.com/ee/ci/yaml/#onlyexcept-basic) to narrow this. But then I remembered that the drawback of this is that it requires explicit action to limit the number of builds, and many times people don't even notice that these builds are running for every branch, which is kinda a waste of resources.

One more question: could we make the default be "the default branch" instead of "master"? This would be a more generic solution as not all Git projects have their default branch set to "master".

**Comment by lachmanfrantisek** [comment]
> I was actually thinking whether it would make sense to have "on any branch" be the default instead. This is the way it's done in GitLab pipelines, and then they use [`only/except`](https://docs.gitlab.com/ee/ci/yaml/#onlyexcept-basic) to narrow this. But then I remembered that the drawback of this is that it requires explicit action to limit the number of builds, and many times people don't even notice that these builds are running for every branch, which is kinda a waste of resources.

Exactly. We can maybe add support (opt-in) for all later. Some alias? Or regex support (e.g. `*`)?

> One more question: could we make the default be "the default branch" instead of "master"? This would be a more generic solution as not all Git projects have their default branch set to "master".

If we can get that info via API, that would be nice. (OGR implementation needed.)

**Comment by TomasTomecek** [comment]
adding this to the Tue arch meeting, I'm lost

**Comment by TomasTomecek** [comment]
We have discussed this and concluded we wanna keep this explicit: if you wanna use branch builds, you need to explicitly list the branch name in the config.
