### ISSUE TITLE
Support more trigers for copr builds

### ISSUE THREAD

**Issue by lachmanfrantisek** [packit-service/packit-service#85]
- [ ] support releases and branch commits as a trigger
- [ ] show the result of the build in the upstream project as a [flag of the commit](https://github.com/packit-service/ogr/blob/master/ogr/services/github.py#L533)

**Comment by lachmanfrantisek** [comment]
Can we add the branch as a trigger and close the other issue?
https://github.com/packit-service/packit-service/issues/13

**Comment by TomasTomecek** [comment]
I propose to close this one since we have more prio things to work on.
