### ISSUE TITLE
Separate worker repo?

### ISSUE THREAD

**Issue by jpopelka** [packit-service/packit-service#9]
Should we eviscerate this repo and put [worker/](https://github.com/packit-service/packit-service/tree/master/packit_service/worker) and [files/run_worker.sh](https://github.com/packit-service/packit-service/blob/master/files/run_worker.sh) to [worker repo](https://github.com/packit-service/packit-worker)?

We have lots of `*-worker` files, which should go there.

**Comment by TomasTomecek** [comment]
Sure, if you feel like this is a good move.

**Comment by TomasTomecek** [comment]
After the sandbox changes I did recently, I vote to split images into two, b/c right now it's 1,5G big:
* the webserver one doesn't need all the worker dependencies
* the worker doesn't need flask & httpd

**Comment by rpitonak** [comment]
closing in favor of #77.

**Comment by jpopelka** [comment]
Reopening since I'm still thinking about splitting the repos completely.
Just creating two images (#77) from one repo isn't enough for me.
This repo would be so much cleaner without all the *-worker* files.

**Comment by TomasTomecek** [comment]
Definitely a good point and I agree it would be much cleaner. But, developing p-s will be one more factor harder with another harder - the question is, if we are okay with that. Especially now that we'll have an API - we would need to figure out how service interact with the DB. Not a big deal, just someone needs to solve this out.

**Comment by jpopelka** [comment]
> developing p-s will be one more factor harder with another repository

which is a sign of bad design, they should be completely independent

**Comment by TomasTomecek** [comment]
> > developing p-s will be one more factor harder with another repository
> 
> which is a sign of bad design, they should be completely independent

feel free to fix it

**Comment by TomasTomecek** [comment]
Discussion outcome:
1. One of the main problems here is ServiceConfig - where it's gonna be and how it's gonna be used.
2. We should do some brief analysis on which code is being imported and used - we should analyze whether this is even possible to be done and if it is, what code changes are needed.
